##########################################
#
# verify_cuda_rfi_sktilde.yaml
#
# Config to test the cuda RFI SKtilde kernel & wrapper
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: INFO

num_gpus: 1
buffer_depth: 4
cpu_affinity: [0,]
sizeof_float: 4
sizeof_int: 4
sizeof_long: 8

# For faster CHORD testing, we're using...
samples_per_data_set: 8192
frame_arrival_period: 5.12e-6 * samples_per_data_set
num_polarizations: 2
num_dishes: 64
num_elements: num_polarizations * num_dishes
num_local_freq: 4

rfi_downsampling_factor: 256

# For random data (as used here) the sk-sigma is ~1.0e-3 but sk~[10, 50].
# To get a non-trivial (not all true or false) RFI mask, need the 
# RFI mask sigmas to be enormous, 2000 is good.
#
# The other thresholds are also set wide, because their effect is multiplicative.
# A mu range of [2, 80] and min_good_frac of 0.25 only gives 60% good SK, the
# rest are 0'd.
rfi_sk_rfimask_sigmas: 2000.0 
rfi_single_feed_min_good_frac: 0.25     # Wide open (0.25) so most feeds are good
rfi_feed_averaged_min_good_frac: 0.25   # Wide open (0.25) so most averaged feeds are good
rfi_mu_min: 2.0       # Should be small (2) to let in many samples.
rfi_mu_max: 80.0      # Should be big (80) to let in many samples.

# Pool
main_pool:
    kotekan_metadata_pool: chordMetadata
    num_metadata_objects: 20 * buffer_depth

# Buffers

host_bf_mask_buffer:
    kotekan_buffer: standard
    num_frames: 1
    frame_size: num_elements
    metadata_pool: main_pool

host_rfi_s012_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / rfi_downsampling_factor) * num_local_freq * 3 * num_elements * sizeof_long
    metadata_pool: main_pool

host_rfi_sktilde_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / rfi_downsampling_factor) * num_local_freq * 3 * sizeof_float
    metadata_pool: main_pool

host_rfi_mask_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_local_freq / 8
    metadata_pool: main_pool

simulated_rfi_sk_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / rfi_downsampling_factor) * num_local_freq * 3 * num_elements * sizeof_float
    metadata_pool: main_pool

simulated_rfi_sktilde_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / rfi_downsampling_factor) * num_local_freq * 3 * sizeof_float
    metadata_pool: main_pool

simulated_rfi_mask_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_local_freq / 8
    metadata_pool: main_pool


# Ringbuffer signalling buffer
host_rfi_s012_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * (samples_per_data_set / rfi_downsampling_factor) * num_local_freq * 3 * num_elements * sizeof_long
    metadata_pool: main_pool

host_rfi_sktilde_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * (samples_per_data_set / rfi_downsampling_factor) * num_local_freq * 3 * sizeof_float
    metadata_pool: main_pool

host_rfi_mask_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * samples_per_data_set * num_local_freq / 8
    metadata_pool: main_pool

gen_rfi_s012:
    log_level: DEBUG
    kotekan_stage: testRFIS012Gen
    out_buf: host_rfi_s012_buffer
    type: random
    bar_mode: false
    downsampling_factor: rfi_downsampling_factor
    num_frames: 2 * buffer_depth

gen_bf_mask:
    type: random8
    kotekan_stage: testDataGen
    out_buf: host_bf_mask_buffer
    name: "bf_mask"
    array_shape: [2, 64 ]
    dim_name: ["P", "D" ]
    num_frames: 1 

run_send_rfi_s012:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_rfi_s012_buffer_in: host_rfi_s012_buffer
        out_buffers:
            host_rfi_s012_ringbuffer_out: host_rfi_s012_ringbuffer
        commands:
        - name: cudaCopyToRingbuffer
          input_size: samples_per_data_set / rfi_downsampling_factor * num_local_freq * 3 * num_elements * sizeof_long
          ring_buffer_size: buffer_depth * input_size
          in_buf: host_rfi_s012_buffer_in
          signal_buf: host_rfi_s012_ringbuffer_out
          gpu_mem_output: rfi_s012_buffer

run_rfi_sktilde:
    log_level: DEBUG
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_bf_mask_buffer: host_bf_mask_buffer
            host_rfi_s012_ringbuffer: host_rfi_s012_ringbuffer
        out_buffers:
            host_rfi_sktilde_ringbuffer: host_rfi_sktilde_ringbuffer
            host_rfi_mask_ringbuffer: host_rfi_mask_ringbuffer
        commands:
        - name: cudaInputData
          do_once: true
          in_buf: host_bf_mask_buffer
          gpu_mem: bf_mask_buffer
        - name: cudaSyncInput
        - name: cudaRFISKtilde
          rfi_S012_name: rfi_s012
          bf_mask_name: bf_mask
          rfi_SKtilde_name: rfi_sktilde
          rfi_RFImask_name: rfi_mask
          num_times: samples_per_data_set
          num_frequencies: num_local_freq
          rfi_num_times: samples_per_data_set / rfi_downsampling_factor

run_recv_rfi_sktilde:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_rfi_sktilde_ringbuffer_in: host_rfi_sktilde_ringbuffer
        out_buffers:
            host_rfi_sktilde_buffer_out: host_rfi_sktilde_buffer
        commands:
        - name: cudaCopyFromRingbuffer
          host_signal: host_rfi_sktilde_ringbuffer_in
          gpu_mem_input: rfi_sktilde_buffer
          output_size: (samples_per_data_set / rfi_downsampling_factor) * num_local_freq * 3 * sizeof_float
          ring_buffer_size: buffer_depth * output_size
          out_buf: host_rfi_sktilde_buffer_out

run_recv_rfi_mask:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_rfi_mask_ringbuffer_in: host_rfi_mask_ringbuffer
        out_buffers:
            host_rfi_mask_buffer_out: host_rfi_mask_buffer
        commands:
        - name: cudaCopyFromRingbuffer
          host_signal: host_rfi_mask_ringbuffer_in
          gpu_mem_input: rfi_mask_buffer
          output_size: samples_per_data_set * num_local_freq / 8
          ring_buffer_size: buffer_depth * output_size
          out_buf: host_rfi_mask_buffer_out


cpu_rfi_sktilde:
    kotekan_stage: gpuSimulateRFISK
    in_rfi_s012_buf: host_rfi_s012_buffer
    in_bf_mask_buf: host_bf_mask_buffer
    out_rfi_sk_buf: simulated_rfi_sk_buffer
    out_rfi_sktilde_buf: simulated_rfi_sktilde_buffer
    out_rfi_mask_buf: simulated_rfi_mask_buffer
    bar_mode: false
    rfi_total_downsampling_factor: rfi_downsampling_factor


check_rfi_sktilde_data:
  kotekan_stage: testDataCheckFloat
  first_buf: host_rfi_sktilde_buffer
  second_buf: simulated_rfi_sktilde_buffer
  max_num_errors_logged: 64
  epsilon: 1.0e-6
  num_frames_to_test: 2 * buffer_depth
  check_metadata: True

check_rfi_rfimask_data:
  kotekan_stage: testDataCheckUchar
  first_buf: host_rfi_mask_buffer
  second_buf: simulated_rfi_mask_buffer
  max_num_errors_logged: 64
  num_frames_to_test: 2 * buffer_depth
  check_metadata: True
