##########################################
#
# verify_cuda_pl_accum.yaml
#
# Config to test the cuda PLMaskAccumulator (n2k s0) kernel.
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: INFO

num_gpus: 1
buffer_depth: 4
cpu_affinity: [0,]
sizeof_float: 4
sizeof_int: 4
sizeof_long: 8

# For faster CHORD testing, we're using...
samples_per_data_set: 1024
frame_arrival_period: 5.12e-6 * samples_per_data_set
num_polarizations: 2
num_dishes: 64
num_elements: num_polarizations * num_dishes
num_local_freq: 8

sub_integration_ntime: 256

# Pool
main_pool:
    kotekan_metadata_pool: chordMetadata
    num_metadata_objects: 20 * buffer_depth

host_pl_mask_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: ((samples_per_data_set / 2) * (num_local_freq / 4) * (num_elements / 8)) / 8
    metadata_pool: main_pool

host_pl_counts_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / sub_integration_ntime) * num_local_freq * num_elements * sizeof_long
    metadata_pool: main_pool

host_pl_lost_counts_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / sub_integration_ntime) * num_local_freq * sizeof_int
    metadata_pool: main_pool

simulated_pl_counts_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / sub_integration_ntime) * num_local_freq * num_elements * sizeof_long
    metadata_pool: main_pool


# Ringbuffer signalling buffer
host_pl_mask_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * ((samples_per_data_set / 2) * (num_local_freq / 4) * (num_elements / 8)) / 8
    metadata_pool: main_pool

gen_pl_mask:
    type: random1x8 
    kotekan_stage: testDataGen
    out_buf: host_pl_mask_buffer
    name: "pl_mask"
    array_shape: [ 8, 2, 2, 8, 8 ]  # = num_times/128, num_freq/4, 2, num_dishes/8, 8
    dim_name: ["T2hi64", "F4", "P", "D8", "T2lo64" ]
    num_frames: 2*buffer_depth  # Must be at least what check_data expects
    meta_time_downsample_factor: 128  # The number of time samples represented by each coarse time index.

run_send_pl_mask:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_pl_mask_buffer_in: host_pl_mask_buffer
        out_buffers:
            host_pl_mask_ringbuffer_out: host_pl_mask_ringbuffer
        commands:
        - name: cudaCopyToRingbuffer
          input_size: (samples_per_data_set / 2) * (num_local_freq / 4) * (num_elements / 8) / 8
          ring_buffer_size: buffer_depth * input_size
          in_buf: host_pl_mask_buffer_in
          signal_buf: host_pl_mask_ringbuffer_out
          gpu_mem_output: pl_mask_buffer

run_pl_counts:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_pl_mask_ringbuffer: host_pl_mask_ringbuffer
        out_buffers:
            host_pl_counts: host_pl_counts_buffer
        commands:
        - name: cudaPLMaskAccumulator
          pl_mask_name: pl_mask
          pl_counts_name: pl_counts
          num_times: samples_per_data_set
          num_frequencies: num_local_freq
        - name: cudaSyncOutput
        - name: cudaOutputData
          gpu_mem: pl_counts_buffer
          out_buf: host_pl_counts

cpu_pl_counts:
    kotekan_stage: gpuSimulatePLMaskAccumulator
    in_buf: host_pl_mask_buffer
    out_buf: simulated_pl_counts_buffer

cpu_pl_lost_counts:
    kotekan_stage: CountLostPLSamplesScalar
    in_buf: host_pl_mask_buffer
    out_buf: host_pl_lost_counts_buffer


check_pl_counts_data:
  kotekan_stage: testDataCheckUlong
  first_buf: host_pl_counts_buffer
  second_buf: simulated_pl_counts_buffer
  max_num_errors_logged: 384
  num_frames_to_test: 2*buffer_depth
  check_metadata: True
