##########################################
#
# verify_cuda_rfi_sktilde.yaml
#
# Config to test the cuda RFI SKtilde kernel & wrapper
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: INFO

num_gpus: 1
buffer_depth: 4
cpu_affinity: [0,]
sizeof_float: 4
sizeof_int: 4
sizeof_long: 8

# For faster CHORD testing, we're using...
samples_per_data_set: 16384
frame_arrival_period: 5.12e-6 * samples_per_data_set
num_polarizations: 2
num_dishes: 64
num_elements: num_polarizations * num_dishes
num_local_freq: 4

rfi_downsampling_factor: 256
rfi_second_downsampling_factor: 16

rfi_sk_rfimask_sigmas: 1.0
rfi_single_feed_min_good_frac: 0.8
rfi_feed_averaged_min_good_frac: 0.8
rfi_mu_min: 2.0
rfi_mu_max: 20.0

rfi_num_times: samples_per_data_set / rfi_downsampling_factor
rfi_num_times_bar: rfi_num_times / rfi_second_downsampling_factor

# Pool
main_pool:
    kotekan_metadata_pool: chordMetadata
    num_metadata_objects: 20 * buffer_depth

# Buffers

host_bf_mask_buffer:
    kotekan_buffer: standard
    num_frames: 1
    frame_size: num_elements
    metadata_pool: main_pool

host_rfi_s012bar_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: rfi_num_times_bar * num_local_freq * 3 * num_elements * sizeof_long
    metadata_pool: main_pool

host_rfi_skbar_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: rfi_num_times_bar * num_local_freq * 3 * num_elements * sizeof_float
    metadata_pool: main_pool

host_rfi_skbartilde_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: rfi_num_times_bar * num_local_freq * 3 * sizeof_float
    metadata_pool: main_pool

simulated_rfi_skbar_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: rfi_num_times_bar * num_local_freq * 3 * num_elements * sizeof_float
    metadata_pool: main_pool

simulated_rfi_skbartilde_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: rfi_num_times_bar * num_local_freq * 3 * sizeof_float
    metadata_pool: main_pool

simulated_rfi_mask_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_local_freq / 8
    metadata_pool: main_pool


# Ringbuffer signalling buffer
host_rfi_s012bar_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * rfi_num_times_bar * num_local_freq * 3 * num_elements * sizeof_long
    metadata_pool: main_pool

host_rfi_skbar_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * rfi_num_times_bar * num_local_freq * 3 * num_elements * sizeof_float
    metadata_pool: main_pool

host_rfi_skbartilde_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * rfi_num_times_bar * num_local_freq * 3 * sizeof_float
    metadata_pool: main_pool

gen_rfi_s012bar:
    type: randomu64
    kotekan_stage: testDataGen
    out_buf: host_rfi_s012bar_buffer
    name: "S012bar"
    array_shape: [ 4, 4, 3, 2, 64 ]
    dim_name: ["Trfibar", "F", "S", "P", "D" ]
    num_frames: 2*buffer_depth  # Must be at least what check_data expects
    meta_time_downsample_factor: rfi_downsampling_factor

gen_bf_mask:
    type: random8
    kotekan_stage: testDataGen
    out_buf: host_bf_mask_buffer
    name: "bf_mask"
    array_shape: [2, 64 ]
    dim_name: ["P", "D" ]
    num_frames: 1 

run_send_rfi_s012bar:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_rfi_s012bar_buffer_in: host_rfi_s012bar_buffer
        out_buffers:
            host_rfi_s012bar_ringbuffer_out: host_rfi_s012bar_ringbuffer
        commands:
        - name: cudaCopyToRingbuffer
          input_size: rfi_num_times_bar * num_local_freq * 3 * num_elements * sizeof_long
          ring_buffer_size: buffer_depth * input_size
          in_buf: host_rfi_s012bar_buffer_in
          signal_buf: host_rfi_s012bar_ringbuffer_out
          gpu_mem_output: rfi_s012bar_buffer

run_rfi_skbar:
    log_level: DEBUG
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_bf_mask_buffer: host_bf_mask_buffer
            host_rfi_s012bar_ringbuffer: host_rfi_s012bar_ringbuffer
        out_buffers:
            host_rfi_skbar_ringbuffer: host_rfi_skbar_ringbuffer
            host_rfi_skbartilde_ringbuffer: host_rfi_skbartilde_ringbuffer
        commands:
        - name: cudaInputData
          do_once: true
          in_buf: host_bf_mask_buffer
          gpu_mem: bf_mask_buffer
        - name: cudaSyncInput
        - name: cudaRFISKbar
          rfi_S012bar_name: rfi_s012bar
          bf_mask_name: bf_mask
          rfi_SKbar_name: rfi_skbar
          rfi_SKbartilde_name: rfi_skbartilde
          num_frequencies: num_local_freq

run_recv_rfi_skbar:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_rfi_skbar_ringbuffer_in: host_rfi_skbar_ringbuffer
        out_buffers:
            host_rfi_skbar_buffer_out: host_rfi_skbar_buffer
        commands:
        - name: cudaCopyFromRingbuffer
          host_signal: host_rfi_skbar_ringbuffer_in
          gpu_mem_input: rfi_skbar_buffer
          output_size: rfi_num_times_bar * num_local_freq * 3 * num_elements * sizeof_float
          ring_buffer_size: buffer_depth * output_size
          out_buf: host_rfi_skbar_buffer_out

run_recv_rfi_skbarbartilde:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_rfi_skbartilde_ringbuffer_in: host_rfi_skbartilde_ringbuffer
        out_buffers:
            host_rfi_skbartilde_buffer_out: host_rfi_skbartilde_buffer
        commands:
        - name: cudaCopyFromRingbuffer
          host_signal: host_rfi_skbartilde_ringbuffer_in
          gpu_mem_input: rfi_skbartilde_buffer
          output_size: rfi_num_times_bar * num_local_freq * 3 * sizeof_float
          ring_buffer_size: buffer_depth * output_size
          out_buf: host_rfi_skbartilde_buffer_out


cpu_rfi_skbar:
    kotekan_stage: gpuSimulateRFISK
    in_rfi_s012_buf: host_rfi_s012bar_buffer
    in_bf_mask_buf: host_bf_mask_buffer
    out_rfi_sk_buf: simulated_rfi_skbar_buffer
    out_rfi_sktilde_buf: simulated_rfi_skbartilde_buffer
    out_rfi_mask_buf: simulated_rfi_mask_buffer
    bar_mode: true
    rfi_total_downsampling_factor: rfi_downsampling_factor * rfi_second_downsampling_factor


check_rfi_data:
  kotekan_stage: testDataCheckFloat
  first_buf: host_rfi_skbar_buffer
  second_buf: simulated_rfi_skbar_buffer
  max_num_errors_logged: 64
  num_frames_to_test: 2 * buffer_depth
  check_metadata: True

# check_rfi_tilde_data:
#   kotekan_stage: testDataCheckFloat
#   first_buf: host_rfi_skbartilde_buffer
#   second_buf: simulated_rfi_skbartilde_buffer
#   max_num_errors_logged: 64
#   num_frames_to_test: 2 * buffer_depth
#   check_metadata: True
