#ifndef GLONASS_CA_CODE_HPP
#define GLONASS_CA_CODE_HPP

#include <array>
#include <stdint.h>

/**
 * GLONASS C/A ranging code -- the FDMA open signal's spreading code, shared by L1OF (~1602 MHz)
 * and L2OF (~1246 MHz) alike.
 *
 * ★★ THE THING THAT MAKES GLONASS DIFFERENT: there is exactly ONE code, and EVERY SATELLITE USES
 * IT. Satellites are separated by FREQUENCY, not by code -- satellite with frequency-channel
 * number k transmits at f0 + k*df (L2: 1246.0 MHz + k*0.4375 MHz, k = -7..+6). So this file has
 * no PRN parameter and no per-satellite table: the entire per-satellite story lives in the
 * carrier, which is why the real work of supporting GLONASS FDMA is a per-PRN frequency offset
 * in the replica bank, not anything here.
 *
 * 511 chips at 511 kcps => a 1 ms period, the same period as GPS L1 C/A (and 511 is likewise
 * 2^9 - 1). Generated by a single 9-stage LFSR, so unlike a Gold code it is a pure m-sequence.
 *
 * DATA-ONLY (no pilot). The navigation message is 50 bps, MANCHESTER encoded to 100 sym/s, so a
 * symbol is 10 ms = ten 1 ms code periods and each 20 ms data bit is a +-/-+ pair of symbols.
 * There is NO secondary/overlay code: wipe at the 10 ms symbol (navwipe_bit_records 10) and the
 * Manchester structure is handled for free, since each 10 ms half is a constant +-1.
 *
 * ★ THE STRUCTURAL TEST THAT MATTERS: a maximal-length sequence has IDEAL two-valued periodic
 * autocorrelation -- exactly -1/511 at every non-zero shift (-54.2 dB), and balance exactly +-1
 * (256 vs 255 chips). That is far sharper than the Gold-code checks the other signals get: an
 * off-by-one in the tap set, the output stage or the shift direction breaks it immediately.
 * glonass_ca_code_check.py asserts both exactly.
 *
 * Sign convention: logic 0 -> +1 (house convention; also PocketSDR's CHIP=(1,-1)).
 * Reference: PocketSDR sdr_code.py gen_code_GLO_CA. A global inversion is immaterial here --
 * the code is its own and has no secondary to stay consistent with.
 */
namespace glonass {

constexpr int CA_CODE_LENGTH = 511;

/// GLONASS FDMA C/A code (L1OF and L2OF), as +-1 chips. No PRN argument by design -- see above.
const std::array<int8_t, CA_CODE_LENGTH>& ca_code();

/// L2OF frequency plan: sky carrier for frequency-channel number k (valid k = -7..+6).
/// L2: 1246.0 MHz + k * 0.4375 MHz. The whole comb spans 1242.94-1248.63 MHz = 5.69 MHz, which
/// is why one 10 MHz tune covers every satellite at once (and L2OC at 1248.06 with it).
constexpr double L2OF_BASE_HZ = 1246.0e6;
constexpr double L2OF_CHANNEL_SPACING_HZ = 437.5e3;
constexpr int L2OF_K_MIN = -7;
constexpr int L2OF_K_MAX = 6;
constexpr double l2of_carrier_hz(int k) {
    return L2OF_BASE_HZ + k * L2OF_CHANNEL_SPACING_HZ;
}

} // namespace glonass

#endif
