# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/.netbeans/remote/teal/iantretyakovs-macbook-pro.local-MacOSX-x86_64/Users/iantretyakov/Documents/CHIME/ch_gpu_kotekan_2/ch_gpu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/.netbeans/remote/teal/iantretyakovs-macbook-pro.local-MacOSX-x86_64/Users/iantretyakov/Documents/CHIME/ch_gpu_kotekan_2/ch_gpu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"binaries\" \"config\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/.netbeans/remote/teal/iantretyakovs-macbook-pro.local-MacOSX-x86_64/Users/iantretyakov/Documents/CHIME/ch_gpu_kotekan_2/ch_gpu/CMakeFiles /root/.netbeans/remote/teal/iantretyakovs-macbook-pro.local-MacOSX-x86_64/Users/iantretyakov/Documents/CHIME/ch_gpu_kotekan_2/ch_gpu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/.netbeans/remote/teal/iantretyakovs-macbook-pro.local-MacOSX-x86_64/Users/iantretyakov/Documents/CHIME/ch_gpu_kotekan_2/ch_gpu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kotekan_libs

# Build rule for target.
kotekan_libs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kotekan_libs
.PHONY : kotekan_libs

# fast build rule for target.
kotekan_libs/fast:
	$(MAKE) -f lib/CMakeFiles/kotekan_libs.dir/build.make lib/CMakeFiles/kotekan_libs.dir/build
.PHONY : kotekan_libs/fast

#=============================================================================
# Target rules for targets named kotekan_testing

# Build rule for target.
kotekan_testing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kotekan_testing
.PHONY : kotekan_testing

# fast build rule for target.
kotekan_testing/fast:
	$(MAKE) -f lib/testing/CMakeFiles/kotekan_testing.dir/build.make lib/testing/CMakeFiles/kotekan_testing.dir/build
.PHONY : kotekan_testing/fast

#=============================================================================
# Target rules for targets named kotekan_processes

# Build rule for target.
kotekan_processes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kotekan_processes
.PHONY : kotekan_processes

# fast build rule for target.
kotekan_processes/fast:
	$(MAKE) -f lib/processes/CMakeFiles/kotekan_processes.dir/build.make lib/processes/CMakeFiles/kotekan_processes.dir/build
.PHONY : kotekan_processes/fast

#=============================================================================
# Target rules for targets named kotekan

# Build rule for target.
kotekan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kotekan
.PHONY : kotekan

# fast build rule for target.
kotekan/fast:
	$(MAKE) -f kotekan/CMakeFiles/kotekan.dir/build.make kotekan/CMakeFiles/kotekan.dir/build
.PHONY : kotekan/fast

#=============================================================================
# Target rules for targets named libinclude

# Build rule for target.
libinclude: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libinclude
.PHONY : libinclude

# fast build rule for target.
libinclude/fast:
	$(MAKE) -f include/CMakeFiles/libinclude.dir/build.make include/CMakeFiles/libinclude.dir/build
.PHONY : libinclude/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... kotekan_libs"
	@echo "... kotekan_testing"
	@echo "... kotekan_processes"
	@echo "... kotekan"
	@echo "... libinclude"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

