import pytest
import numpy as np

from kotekan import runner

prod_config = {
    "buffer_depth": 5,
    "samples_per_data_set": 16384,
    "num_local_freq": 12,
    "sub_integration_ntime": 8192,
    "num_polarizations": 2,
    "num_dishes": 512,
}

small_config = {
    "buffer_depth": 2,
    "samples_per_data_set": 1024,
    "num_local_freq": 4,
    "sub_integration_ntime": 128,
    "num_polarizations": 2,
    "num_dishes": 8,
}


@pytest.fixture(
    scope="module",
    params=[
        (small_config, [[1, 0, 7, 255, 16]], ),
        (prod_config, [[255],[0],
                       [2, 3, 5, 7, 11, 13, 17, 23, 29, 31, 37]], ),
    ],
)
def setup(request):
    """
    Generate the base config and setup parameters to run a test. This (and the other fixtures) should provide *everything* needed to test a stage.

    Parameters
    ----------
    request : pytest magic
        Provides the parameterized values.

    Returns
    -------
    tuple
        The base config, as well as parameters to generate input SK data
    """
    config, pl_vals = request.param
    return config, pl_vals


@pytest.fixture(scope="module")
def plmask_data(setup):
    """
    Generate a list of input SKtilde frames in ChordBuffers

    Parameters
    ----------
    setup : fixture
        Includes the base config as well as SK generation parameters

    Returns
    -------
    List of ChordBuffers each containing an SKtilde frame.
    """

    config, pl_vals = setup

    num_frames = 2 * config["buffer_depth"]

    bufs = []

    for idx in range(num_frames):

        seq_num = idx * config["samples_per_data_set"]

        data = np.empty((config["samples_per_data_set"] // 128, config["num_local_freq"] // 4, config["num_polarizations"], config["num_dishes"]//8, 8), dtype=np.uint8)

        meta = runner.chordbuffer.get_metadata(
                "pl_mask", "uint1x8", ("T2hi64", "F4", "P", "D8", "T2lo64")
        )
        meta["fpga_seq_num"] = seq_num
        meta["time_downsampling_fpga"] = 128

        # Loop over the given sk and sigma lists. Each should be a list-of-lists, with frequency
        # as the outer axis and time as the inner. Values are directly assigned to the SKtilde buffer.

        t16_0 = (idx * config["samples_per_data_set"]) // 16
        t16_1 = ((idx+1) * config["samples_per_data_set"]) // 16

        for f4 in range(config["num_local_freq"] // 4):
            pl_f = pl_vals[f4 % len(pl_vals)]

            pl_timeseries = np.empty(config["samples_per_data_set"] // 16, dtype=np.uint8)

            for t16 in range(t16_0, t16_1):
                pl_timeseries[t16-t16_0] = pl_f[t16 % len(pl_f)]

            pl_timeseries_2d = pl_timeseries.reshape((-1, 8))
            
            data[:, f4, :, :, :] = pl_timeseries_2d[:, None, None, :]

        bufs.append(runner.chordbuffer.ChordBuffer(data, meta))

    return bufs


@pytest.fixture(scope="module")
def pllostcounts_data(tmpdir_factory, setup, plmask_data):
    """
    Run the CountLostPLSamplesScalar stage on the given input and yield the output buffers.

    Parameters
    ----------
    tmpdir_factory : pytest magic
        Generates temporary directories
    setup : fixture
        Includes the base config as well as PL mask generation parameters
    plmask_data : fixture
        A List of ChordBuffers for input

    Yields
    ------
    List of ChordBuffers each containing an RFIFrameMask generated by RfiFrameMask.
    """

    config, _ = setup

    num_frames = len(plmask_data)

    tmpdir = tmpdir_factory.mktemp("plcountlost")

    # Make input buffer and write the files for it to read.
    input_buffer = runner.ReadChordBuffer(str(tmpdir), plmask_data)
    input_buffer.write()

    # Make the output buffer we'll read from
    dump_buffer = runner.DumpChordBuffer(
        str(tmpdir),
        shape=(
            config["samples_per_data_set"] // config["sub_integration_ntime"],
            config["num_local_freq"],
        ),
        dtype=np.int32,
        max_frames=num_frames,
    )

    # The test stage!
    test = runner.KotekanStageTester(
        "CountLostPLSamplesScalar",
        {},
        input_buffer,
        dump_buffer,
        config,
    )

    test.run()

    yield dump_buffer.load()


def count_lost_samples(plmask, config):
    """
    Apply the thresholds in `config` to generate a frame mask from the SK data in sktilde, for testing against the RfiFrameMask Kotekan stage.

    Parameters
    ----------
    sktilde : ChordBuffer
        The input SK data
    config : dict
        The base config for the run

    Returns
    -------
    ndarray (num_integrations, num_frequency), uint8
        The frame mask. 1 for a good integration, 0 for a bad integration.
    """

    # Number of integrations per frame, and trfi per integration
    nint = config["samples_per_data_set"] // config["sub_integration_ntime"]

    nf = config["num_local_freq"]

    # Default to 0 (good)
    lost_counts = np.zeros((nint, nf), dtype=np.int32)

    # Loop over integrations
    for tint in range(nint):

        t0 = tint * config["sub_integration_ntime"]
        t1 = (tint + 1) * config["sub_integration_ntime"]

        tpl0 = t0 // 128
        tpl1 = t1 // 128

        lost_counts_f4 = (config["sub_integration_ntime"] - 2 * np.bitwise_count(plmask.data[tpl0:tpl1, :, 0, 0, :]).astype(np.int32).sum(axis=(0, 2)))

        for f in range(config["num_local_freq"]):
            lost_counts[tint, f] = lost_counts_f4[f//4]

    return lost_counts


def test_meta(pllostcounts_data, setup):
    # Test the metadata

    config, _ = setup

    for idx, frame in enumerate(pllostcounts_data):

        assert frame.metadata["name"] == "pl_lost_counts_scalar"
        assert (frame.metadata["dim_names"] == ["Tc", "F"]).all()
        assert (
            frame.metadata["time_downsampling_fpga"] == config["sub_integration_ntime"]
        )
        assert frame.metadata["fpga_seq_num"] == idx * config["samples_per_data_set"]


def test_pl_lost_counts(pllostcounts_data, setup, plmask_data):
    # Test the frame mask data

    config, _ = setup

    # Should have same number of frames!
    assert len(pllostcounts_data) == len(plmask_data)

    for idx, frame in enumerate(pllostcounts_data):

        # Check output is the right shape and type
        assert frame.data.shape == (
            config["samples_per_data_set"] // config["sub_integration_ntime"],
            config["num_local_freq"],
        )
        assert frame.data.dtype == np.int32

        # Generate the correct frame mask
        pl_lost_counts = count_lost_samples(plmask_data[idx], config)

        # Confirm the Kotekan and Python masks have same shape and type
        assert frame.data.shape == pl_lost_counts.shape
        assert frame.data.dtype == pl_lost_counts.dtype

        # Check the masks are identical
        assert (frame.data == pl_lost_counts).all()
