# IO feature detection and setup: ASDF, GDAL, HDF5 + HighFive

include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/../Color.cmake)

# ASDF
if ("${USE_ASDF}" STREQUAL "AUTO")
    find_package(asdf-cxx)
    if (ASDF_CXX_FOUND)
        add_definitions(-DWITH_ASDF_CXX)
        set(ASDF_REASON "auto-detected")
        kmsg_ok("ASDF found (autodetected): enabling ASDF stages (disable with -DUSE_ASDF=OFF)")
    else ()
        set(ASDF_REASON "disabled, not found")
        kmsg_warn("ASDF not found (default AUTO, continuing without).")
    endif ()
elseif ("${USE_ASDF}" STREQUAL "ON")
    find_package(asdf-cxx)
    if (ASDF_CXX_FOUND)
        add_definitions(-DWITH_ASDF_CXX)
        set(ASDF_REASON "enabled, found")
        kmsg_ok("ASDF explicitly enabled via -DUSE_ASDF=ON")
    else ()
        set(ASDF_REASON "enabled, not found")
        set(USE_ASDF "OFF")
        kmsg_error("ASDF not found when requested!")
    endif ()
else () # OFF
    set(ASDF_REASON "disabled")
    kmsg_status("ASDF explicitly disabled via -DUSE_ASDF=OFF")
endif ()


# GDAL
if ("${USE_GDAL}" STREQUAL "AUTO")
    find_package(GDAL)
    if (GDAL_FOUND)
        add_definitions(-DWITH_GDAL)
        set(GDAL_REASON "auto-detected")
        kmsg_ok("GDAL found: enabling GDAL stages (disable with -DUSE_GDAL=OFF)")
    else ()
        set(GDAL_REASON "disabled, not found")
        kmsg_warn("GDAL not found (default AUTO, continuing without).")
    endif ()
elseif ("${USE_GDAL}" STREQUAL "ON")
    find_package(GDAL)
    if (GDAL_FOUND)
        add_definitions(-DWITH_GDAL)
        set(GDAL_REASON "enabled, found")
        kmsg_ok("GDAL explicitly enabled via -DUSE_GDAL=ON")
    else ()
        set(GDAL_REASON "enabled, not found")
        set(USE_GDAL "OFF")
        kmsg_error("GDAL not found when requested!")
    endif ()
else () # OFF
    set(GDAL_REASON "disabled")
    kmsg_status("GDAL explicitly disabled via -DUSE_GDAL=OFF")
endif ()


# HDF5 + HighFive + HDF5Plugin
if (${USE_HDF5} STREQUAL "AUTO" OR "${USE_HDF5}" STREQUAL "ON")
    find_package(HDF5)
    find_package(HighFive)
    # Try to locate the runtime HDF5 plugin directory (e.g., libh5blosc)
    # This avoids runtime errors when HDF5_PLUGIN_PATH is not set.
    find_package(HDF5Plugin)

    if (HDF5_FOUND AND HighFive_FOUND AND HDF5Plugin_PLUGIN_DIR)
        add_definitions(-DWITH_HDF5)
        if (${USE_HDF5} STREQUAL "AUTO")
            set(HDF5_REASON "auto-detected")
        else ()
            set(HDF5_REASON "enabled, found")
        endif ()
        kmsg_ok("HDF5 found: enabling HDF5 stages (disable with -DUSE_HDF5=OFF)")

        set(KOTEKAN_HDF5_PLUGIN_DIR
                "${HDF5Plugin_PLUGIN_DIR}"
                CACHE INTERNAL "Detected HDF5 plugin directory for runtime use")
        kmsg_status("HDF5 plugin dir detected: ${KOTEKAN_HDF5_PLUGIN_DIR} (will set at runtime)")
    else ()
        set(_missing_hdf5 "")
        if (NOT HDF5_FOUND)
            list(APPEND _missing_hdf5 "HDF5")
        endif ()
        if (NOT HighFive_FOUND)
            list(APPEND _missing_hdf5 "HighFive")
        endif ()
        if (NOT HDF5Plugin_PLUGIN_DIR)
            list(APPEND _missing_hdf5 "HDF5Plugin")
            set(KOTEKAN_HDF5_PLUGIN_DIR "" CACHE INTERNAL "")
            kmsg_warn("HDF5 plugins not found (libh5blosc, etc.). Set HDF5_PLUGIN_PATH if needed.")
        endif ()

        if (${USE_HDF5} STREQUAL "AUTO")
            set(HDF5_REASON "auto-detected")
            kmsg_warn("HDF5 not fully found (missing: ${_missing_hdf5}); HDF5 stages disabled.")
        else ()
            set(HDF5_REASON "enabled, not found")
            kmsg_error("HDF5 not fully found (missing: ${_missing_hdf5}) when requested! HDF5 stages disabled.")
        endif ()

        # Set this at the end so the informative "AUTO" message can be sent.
        set(USE_HDF5 "OFF")

    endif ()
else ()
    kmsg_status("HDF5 disabled via -DUSE_HDF5=OFF")
endif ()
