# GPU feature detection for CUDA, HIP, and OpenCL.
# Normalizes the USE_* tri-state toggles, emits status messaging, and keeps

include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/../Color.cmake)

set(GPU_MODULES "")

# CUDA
if ("${USE_CUDA}" STREQUAL "AUTO" OR "${USE_CUDA}" STREQUAL "ON")
    include(CheckLanguage)
    check_language(CUDA)
    if (CMAKE_CUDA_COMPILER)
        enable_language(CUDA)
        find_package(CUDAToolkit)
        if (CUDAToolkit_FOUND)
            add_definitions(-DWITH_CUDA)
            list(APPEND GPU_MODULES "CUDA ")
            if ("${USE_CUDA}" STREQUAL "AUTO")
                set(CUDA_REASON "auto-detected")
                kmsg_ok(
                        "CUDA found (autodetected): enabling CUDA stages (disable with -DUSE_CUDA=OFF)")
            else ()
                set(CUDA_REASON "enabled, found")
                kmsg_ok("CUDA explicitly enabled via -DUSE_CUDA=ON")
            endif ()
            if (CUDAToolkit_INCLUDE_DIRS)
                kmsg_status("Compiling with CUDA tools in ${CUDAToolkit_INCLUDE_DIRS}.")
            endif ()
        else ()
            if ("${USE_CUDA}" STREQUAL "AUTO")
                set(CUDA_REASON "disabled, toolkit not found")
                kmsg_warn(
                        "CUDAToolkit not found (default AUTO, continuing without).")
            else ()
                set(CUDA_REASON "enabled, toolkit not found")
                kmsg_error(
                        "CUDAToolkit not found when requested! Disable with -DUSE_CUDA=OFF.")
            endif ()
        endif ()
    else ()
        if ("${USE_CUDA}" STREQUAL "AUTO")
            set(CUDA_REASON "disabled, compiler not found")
            kmsg_warn(
                    "CUDA compiler not available (default AUTO, continuing without).")
        else ()
            set(CUDA_REASON "enabled, compiler not found")
            kmsg_error("CUDA compiler not available when requested! Disable with -DUSE_CUDA=OFF.")
        endif ()
    endif ()
else ()
    set(CUDA_REASON "disabled")
    kmsg_status("CUDA explicitly disabled via -DUSE_CUDA=OFF")
endif ()


# HIP
if ("${USE_HIP}" STREQUAL "AUTO" OR "${USE_HIP}" STREQUAL "ON")
    find_package(HIP)
    if (HIP_FOUND)
        add_definitions(-DWITH_HIP)
        list(APPEND GPU_MODULES "HIP ")
        if ("${USE_HIP}" STREQUAL "AUTO")
            set(HIP_REASON "auto-detected")
            kmsg_ok("HIP found (autodetected): enabling HIP GPU backend (disable with -DUSE_HIP=OFF)")
        else ()
            set(HIP_REASON "enabled, found")
            kmsg_ok("HIP explicitly enabled via -DUSE_HIP=ON")
        endif ()
    else ()
        if ("${USE_HIP}" STREQUAL "AUTO")
            set(HIP_REASON "disabled, not found")
            kmsg_warn("HIP not found (default AUTO, continuing without).")
        else ()
            set(HIP_REASON "enabled, not found")
            kmsg_error("HIP not found when requested! Disable with -DUSE_HIP=OFF.")
        endif ()
    endif ()
else ()
    set(HIP_REASON "disabled")
    kmsg_status("HIP explicitly disabled via -DUSE_HIP=OFF")
endif ()


# OpenCL
if ("${USE_OPENCL}" STREQUAL "AUTO" OR "${USE_OPENCL}" STREQUAL "ON")
    if (NOT DEFINED ENV{AMDAPPSDKROOT})
        set(ENV{AMDAPPSDKROOT} /opt/rocm/opencl)
    endif ()
    find_package(OPENCL)
    if (OPENCL_FOUND)
        list(APPEND GPU_MODULES "OpenCL ")
        install(DIRECTORY lib/opencl/kernels DESTINATION /var/lib/kotekan/opencl)
        if ("${USE_OPENCL}" STREQUAL "AUTO")
            set(OPENCL_REASON "auto-detected")
            kmsg_ok("OpenCL found (autodetected): enabling OpenCL stages (disable with -DUSE_OPENCL=OFF)")
        else ()
            set(OPENCL_REASON "enabled, found")
            kmsg_ok("OpenCL explicitly enabled via -DUSE_OPENCL=ON")
        endif ()
    else ()
        if ("${USE_OPENCL}" STREQUAL "AUTO")
            set(OPENCL_REASON "disabled, not found")
            kmsg_warn("OpenCL not found (default AUTO, continuing without).")
        else ()
            set(OPENCL_REASON "enabled, not found")
            kmsg_error("OpenCL not found when requested! Disable with -DUSE_OPENCL=OFF.")
        endif ()
    endif ()
else ()
    set(OPENCL_REASON "disabled")
    kmsg_status("OpenCL explicitly disabled via -DUSE_OPENCL=OFF")
endif ()
