# GPU feature detection and setup: CUDA, OpenCL, HIP

include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/../Color.cmake)

set(GPU_MODULES "")
set(OPENCL_ENABLED OFF)
set(OPENCL_REASON "disabled")
set(CUDA_ENABLED OFF)
set(CUDA_REASON "disabled")
set(HIP_ENABLED OFF)
set(HIP_REASON "disabled")

if(${USE_OPENCL})
    set(ENV{AMDAPPSDKROOT} /opt/rocm/opencl)
    find_package(OPENCL REQUIRED)
    set(USE_OPENCL ${OPENCL_FOUND})
    if(${USE_OPENCL})
        list(APPEND GPU_MODULES "OpenCL ")
        set(OPENCL_ENABLED ON)
        set(OPENCL_REASON "found")
        install(DIRECTORY lib/opencl/kernels DESTINATION /var/lib/kotekan/opencl)
    endif()
endif()

if(${USE_HIP})
    find_package(HIP)
    set(USE_HIP ${HIP_FOUND})
    if(${USE_HIP})
        add_definitions(-DWITH_HIP)
        list(APPEND GPU_MODULES "HIP ")
        set(HIP_ENABLED ON)
        set(HIP_REASON "found")
    else()
        set(HIP_ENABLED OFF)
        set(HIP_REASON "not found")
    endif()
endif()

if(${USE_CUDA})
    set(CUDA_TOOLKIT_ROOT_DIR /usr/local/cuda)
    set(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)
    set(USE_CUDA ${CUDA_FOUND})
    enable_language(CUDA)
    find_package(CUDAToolkit REQUIRED)
    add_definitions(-DWITH_CUDA)
    list(APPEND GPU_MODULES "CUDA ")
    kmsg_status("Compiling with CUDA tools in ${CUDAToolkit_INCLUDE_DIRS}.")
    set(CUDA_ENABLED ON)
    set(CUDA_REASON "found")
endif()

# (Summary printed at end; avoid intermediate prints)
