# GPU feature detection and setup: CUDA, OpenCL, HIP

include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/../Color.cmake)

set(GPU_MODULES "")
set(OPENCL_ENABLED OFF)
set(OPENCL_REASON "disabled")
set(CUDA_ENABLED OFF)
get_property(_ktk_cuda_cache_has CACHE CUDA_REASON PROPERTY TYPE SET)
if(_ktk_cuda_cache_has)
    get_property(CUDA_REASON CACHE CUDA_REASON PROPERTY VALUE)
else()
    set(CUDA_REASON "disabled")
endif()
set(HIP_ENABLED OFF)
set(HIP_REASON "disabled")

if(${USE_CUDA})
    include(CheckLanguage)
    check_language(CUDA)
    if(CMAKE_CUDA_COMPILER)
        enable_language(CUDA)
        find_package(CUDAToolkit)
        if(CUDAToolkit_FOUND)
            add_definitions(-DWITH_CUDA)
            list(APPEND GPU_MODULES "CUDA ")
            kmsg_ok(
                "CUDA found: enabling CUDA stages (disable with -DUSE_CUDA=OFF)")
            kmsg_status("Compiling with CUDA tools in ${CUDAToolkit_INCLUDE_DIRS}.")
            set(CUDA_ENABLED ON)
            set(CUDA_REASON "found")
            set(CUDA_REASON "${CUDA_REASON}" CACHE STRING "CUDA detection summary" FORCE)
        else()
            set(USE_CUDA OFF CACHE BOOL "Build CUDA GPU Framework" FORCE)
            set(CUDA_ENABLED OFF)
            set(CUDA_REASON "CUDAToolkit not found")
            kmsg_error(
                "CUDA requested but CUDAToolkit not found; disabling CUDA support.")
            set(CUDA_REASON "${CUDA_REASON}" CACHE STRING "CUDA detection summary" FORCE)
        endif()
    else()
        set(USE_CUDA OFF CACHE BOOL "Build CUDA GPU Framework" FORCE)
        set(CUDA_ENABLED OFF)
        set(CUDA_REASON "compiler not found")
        kmsg_error("CUDA compiler not available; disabling CUDA support.")
        set(CUDA_REASON "${CUDA_REASON}" CACHE STRING "CUDA detection summary" FORCE)
    endif()
else()
    if(NOT ("${CUDA_REASON}" STREQUAL "CUDAToolkit not found" OR
            "${CUDA_REASON}" STREQUAL "compiler not found"))
        set(CUDA_REASON "disabled")
    endif()
    set(CUDA_REASON "${CUDA_REASON}" CACHE STRING "CUDA detection summary" FORCE)
    kmsg_status("CUDA disabled via -DUSE_CUDA=OFF")
endif()

if(${USE_HIP})
    find_package(HIP REQUIRED)
    set(USE_HIP ${HIP_FOUND})
    if(${USE_HIP})
        add_definitions(-DWITH_HIP)
        list(APPEND GPU_MODULES "HIP ")
        set(HIP_ENABLED ON)
        set(HIP_REASON "found")
    else()
        set(HIP_ENABLED OFF)
        set(HIP_REASON "not found")
    endif()
endif()

if(${USE_OPENCL})
    set(ENV{AMDAPPSDKROOT} /opt/rocm/opencl)
    find_package(OPENCL REQUIRED)
    set(USE_OPENCL ${OPENCL_FOUND})
    if(${USE_OPENCL})
        list(APPEND GPU_MODULES "OpenCL ")
        set(OPENCL_ENABLED ON)
        set(OPENCL_REASON "found")
        install(DIRECTORY lib/opencl/kernels DESTINATION /var/lib/kotekan/opencl)
    endif()
endif()

# (Summary printed at end; avoid intermediate prints)
