# IO feature detection and setup: ASDF, GDAL, HDF5 + HighFive

include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/../Color.cmake)

# ASDF
set(ASDF_ENABLED OFF)
set(ASDF_REASON "disabled")
if(${USE_ASDF})
    find_package(asdf-cxx QUIET)
    if(ASDF_CXX_FOUND)
        add_definitions(-DWITH_ASDF_CXX)
        set(ASDF_ENABLED ON)
        set(ASDF_REASON "found")
        kmsg_ok("ASDF found: enabling ASDF stages (disable with -DUSE_ASDF=OFF)")
    else()
        set(USE_ASDF OFF)
        set(ASDF_ENABLED OFF)
        set(ASDF_REASON "not found")
        kmsg_warn("ASDF not found; ASDF stages disabled.")
    endif()
else()
    kmsg_status("ASDF disabled via -DUSE_ASDF=OFF")
endif()

# GDAL
set(GDAL_ENABLED OFF)
set(GDAL_REASON "disabled")
if(${USE_GDAL})
    find_package(GDAL QUIET)
    if(GDAL_FOUND)
        add_definitions(-DWITH_GDAL)
        set(GDAL_ENABLED ON)
        set(GDAL_REASON "found")
        kmsg_ok("GDAL found: enabling GDAL stages (disable with -DUSE_GDAL=OFF)")
    else()
        set(USE_GDAL OFF)
        set(GDAL_ENABLED OFF)
        set(GDAL_REASON "not found")
        kmsg_warn("GDAL not found; GDAL stages disabled.")
    endif()
else()
    kmsg_status("GDAL disabled via -DUSE_GDAL=OFF")
endif()

# HDF5 + HighFive
set(HDF5_ENABLED OFF)
set(HDF5_REASON "disabled")
if(${USE_HDF5})
    find_package(HDF5 QUIET)
    find_package(HighFive QUIET)
    if(HDF5_FOUND AND HighFive_FOUND)
        add_definitions(-DWITH_HDF5)
        set(HDF5_ENABLED ON)
        set(HDF5_REASON "found")
        kmsg_ok("HDF5 found: enabling HDF5 stages (disable with -DUSE_HDF5=OFF)")
    else()
        set(USE_HDF5 OFF)
        set(_missing_hdf5 "")
        if(NOT HDF5_FOUND)
            list(APPEND _missing_hdf5 "HDF5")
        endif()
        if(NOT HighFive_FOUND)
            list(APPEND _missing_hdf5 "HighFive")
        endif()
        set(HDF5_ENABLED OFF)
        set(HDF5_REASON "missing: ${_missing_hdf5}")
        kmsg_warn("HDF5 not fully found (missing: ${_missing_hdf5}); HDF5 stages disabled.")
    endif()
else()
    kmsg_status("HDF5 disabled via -DUSE_HDF5=OFF")
endif()
