#!/usr/bin/env python3
"""GATE for #51's fast code loop: does --fast-trim-hz actually actuate, and safely?

    python3 scripts/gnss/fast_trim_e2e.py [--hz 5] [--seconds 20] [--keep]

WHY THIS EXISTS. --fast-trim-hz moves the code loop off the ~12 s policy cycle onto a thread
running at the telemetry rate, because the loop's authority is a step PER UPDATE and at 12 s it
was 23x slower than the measured drift. That is an ACTUATOR change: it POSTs seeds to every
tracker several times a second. Debugging an actuator against the sky is how a bad one gets
blamed on the weather, so it is exercised here first -- real broker, real gather, real
bufferSend/bufferRecv, synthetic records with a KNOWN discriminator.

WHAT IT COMPOSES, rather than reinvents:
  * telem_e2e.py's fixture + kotekan config: real GnssTelemPack -> bufferSend -> bufferRecv ->
    GnssTelemGather, serving a comb whose per-channel E/P/L are 0.5 / 1.0 / 0.25. That makes
    the fleet discriminator EXACTLY +0.6 and q EXACTLY 6.4 -- so every number below is
    predicted, not merely plausible.
  * a minimal fake pipeline (get_detections / get_status / set_seeds), in the spirit of
    e2e_broker.py, capturing every POST with its arrival time.
  * the REAL broker, with --telem-gather --telem-dll --fast-trim-hz.

THE FOUR THINGS IT CHECKS, each written against a specific way this could be wrong:

  [1] IT ACTUATES AT THE REQUESTED RATE. POSTs must arrive at ~--hz, not at the policy cycle.
      This is the whole point; a fast loop that silently falls back to the cycle would look
      exactly like the bug it fixes.

  [2] THE TRIM MOVES THE RIGHT WAY, AT THE PREDICTED SIZE. disc = +0.6 -> tau = -0.6/4 = -0.15
      -> step = dll_gain * tau = -0.0375 chips per update. A sign error here drives the tap
      AWAY from the peak faster than the old loop ever could, and on sky that is
      indistinguishable from "the satellite faded".

  [3] ⚠️ CONSECUTIVE FAST POSTS DIFFER ONLY IN code_phase_chips. The fast path substitutes one
      field into the policy cycle's own payload precisely so it cannot drop carrier_trim_hz,
      the joint-state terms or nav bits -- and a POST that drops a field ZEROES it at the
      tracker. This is the assertion that an actuator is not quietly undoing another loop.

  [4] IT ARMS ONLY WHAT POLICY ARMED. Every PRN in a fast POST must be one the fixture makes
      present. A fast loop that invents its own presence would bypass every gate and floor.
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import http.server

HERE = os.path.dirname(os.path.abspath(__file__))
K = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(K, "python", "scripts", "gnss"))

import telem_e2e as T  # noqa: E402  (fixture + kotekan config, reused verbatim)

FAKE_PORT = 12893
POSTS = []          # (t_wall, [seed dicts])
DETS = []           # the one detection the fake search serves
LOCK = threading.Lock()


class Fake(http.server.BaseHTTPRequestHandler):
    """Detections / combiner status / seed sink. Deliberately minimal: with --telem-dll the
    COMB is the discriminator, so an empty /get_status is correct -- presence, floors and the
    trim all come from the gather, which is the path under test."""

    def log_message(self, *a):
        pass

    def _send(self, obj):
        b = json.dumps(obj).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(b)))
        self.end_headers()
        self.wfile.write(b)

    def do_GET(self):
        # ⚠️ THE DETECTION IS GENERATED BY THE e2e BINARY, NOT HAND-WRITTEN. A seed the broker
        # refuses (bad ref_hop, impossible geometry) produces an empty payload, an empty
        # fast_tmpl, and a gate that passes vacuously because the fast loop had nothing to
        # actuate on. Its PRN is chosen to be one the telemetry fixture makes LIVE, or the
        # policy set and the comb set never intersect.
        self._send(DETS if self.path.endswith("/get_detections") else [])

    def do_POST(self):
        n = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(n) if n else b"[]"
        if self.path.endswith("/set_seeds"):
            try:
                with LOCK:
                    POSTS.append((time.time(), json.loads(body.decode())))
            except Exception:
                pass
        self._send({"ok": True})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hz", type=float, default=5.0)
    ap.add_argument("--seconds", type=float, default=20.0)
    ap.add_argument("--keep", action="store_true")
    a = ap.parse_args()

    d = tempfile.mkdtemp(prefix="fast_trim_e2e-")
    det_prn = T.LIVE_PRNS[0]
    det_path = os.path.join(d, "det.json")
    print("generating a real detection for PRN %d (e2e --emit-detection, ~20 s)..." % det_prn)
    subprocess.run([os.path.join(HERE, "e2e"), "--prn", str(det_prn),
                    "--emit-detection", det_path],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=300)
    if not os.path.exists(det_path):
        raise SystemExit("e2e did not emit a detection -- cannot seed the broker")
    DETS.extend(json.load(open(det_path)))
    print("detection PRN %d snr %.0f ref_hop %d"
          % (DETS[0]["prn"], DETS[0]["snr"], DETS[0]["ref_hop"]))
    # ⚠️ COMB VALUES CHOSEN SO EVERY NUMBER BELOW IS PREDICTED, NOT PLAUSIBLE. Per channel
    # E/P/L = 0.5 / 1.0 / 0.25 with unit energy gives, per instance, e = 0.25, p = 1, l =
    # 0.0625; summed over instances the ratios are unchanged, so
    #     disc = (E-L)/(E+L) = (0.25-0.0625)/0.3125 = +0.6
    #     q    = 2P/(E+L)    = 2/0.3125             = 6.4   (clears the 2.2 fallback floor)
    #     tau  = -0.6/4 = -0.15  ->  step = dll_gain * tau = -0.0375 chips per update
    # The fixture's DEFAULT comb carries provenance marks instead, which are arbitrary as
    # amplitudes -- I used them first and got 0 present, which is the correct answer to the
    # wrong question.
    for inst, start in T.INSTANCES:
        T.write_record_files(d, inst, start, comb_epl=(0.5, 1.0, 0.25))
    cfg = T.write_config(d)
    klog = os.path.join(d, "kotekan.log")
    kp = subprocess.Popen([T.kotekan_binary(), "--config", cfg,
                           "--bind-address", "127.0.0.1:%d" % T.PORT_REST],
                          stdout=open(klog, "wb"), stderr=subprocess.STDOUT)
    srv = http.server.ThreadingHTTPServer(("127.0.0.1", FAKE_PORT), Fake)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    base = "http://127.0.0.1:%d" % FAKE_PORT
    print("scratch  %s\ngather   127.0.0.1:%d\nfake     %s" % (d, T.PORT_SERVE, base))

    blog = os.path.join(d, "broker.log")
    # Mirrors e2e_broker.py's known-good invocation (same signal geometry, deliberately no
    # almanac / dead-reckon / cl-assist -- those need BRDC and a live clock, and the question
    # here is the ACTUATOR, not the sky model). dll-gain is the production 0.25, because the
    # step size is exactly what [2] predicts from it.
    cmd = [sys.executable, "-u", "python/scripts/gnss/gps_distributed_broker.py",
           "--rest-url", base,
           "--detectors", base + "/gps_search",
           "--trackers", base + "/gps_track",
           "--combiner", base + "/gps_combine",
           "--dll-combiners", base + "/gps_combine",
           "--constellation", "G", "--carrier-hz", "1176.45e6",
           "--chip-rate-hz", "10.23e6", "--code-length", "10230",
           "--hops-per-sec", "195312.5",
           "--signal", "gps_l5",          # sets the TELEMETRY CHAIN KEY, which must equal the
                                          # chain the fixture stamps on every frame or the
                                          # store lookup silently finds nothing
           "--seed-doppler", "det", "--acquire-snr", "30",
           "--dll-gain", "0.25", "--carrier-gain", "0.0",
           "--interval", "2",
           "--telem-gather", "127.0.0.1:%d" % T.PORT_SERVE,
           "--telem-dll",
           "--telem-dll-windows", "4",
           "--fast-trim-hz", str(a.hz),
           "--fast-trim-windows", "4"]
    bp = subprocess.Popen(cmd, cwd=K, stdout=open(blog, "wb"),
                          stderr=subprocess.STDOUT)
    t0 = time.time()
    try:
        time.sleep(a.seconds)
    finally:
        for p in (bp, kp):
            p.terminate()
        try:
            bp.wait(5)
            kp.wait(5)
        except Exception:
            pass
        srv.shutdown()

    with LOCK:
        posts = list(POSTS)
    span = time.time() - t0
    fails = []
    print("\nposts    %d over %.1f s = %.2f Hz" % (len(posts), span, len(posts) / span))

    # -- [1] it actuates at the requested rate -------------------------------------------
    rate = len(posts) / span
    if rate < 0.5 * a.hz:
        fails.append("[1] POST rate %.2f Hz is far below the requested %.1f Hz -- the fast "
                     "loop is not running (check --telem-gather reached it, and the log)"
                     % (rate, a.hz))
    # the policy cycle alone would give ~1/interval; prove we are well above it
    if rate < 1.0:
        fails.append("[1] POST rate %.2f Hz is at or below the policy cycle -- no speedup"
                     % rate)

    # -- [2]/[3]/[4]: walk the captured seeds --------------------------------------------
    per_prn = {}
    for t, seeds in posts:
        for s in seeds:
            if isinstance(s, dict) and "prn" in s:
                per_prn.setdefault(int(s["prn"]), []).append((t, s))
    print("PRNs     %s (fixture live PRNs %s)" % (sorted(per_prn), T.LIVE_PRNS))

    for prn in per_prn:
        if prn not in T.LIVE_PRNS:
            fails.append("[4] PRN %d was POSTed but is not one the fixture makes present -- "
                         "the fast loop is arming PRNs policy did not" % prn)

    moved = 0
    for prn, seq in sorted(per_prn.items()):
        if len(seq) < 4:
            continue
        cps = [s.get("code_phase_chips") for _t, s in seq if s.get("code_phase_chips") is not None]
        if len(cps) < 4:
            continue
        # [2] direction + size. disc = +0.6 -> tau = -0.15 -> step = 0.25 * -0.15 = -0.0375
        steps = [b - a2 for a2, b in zip(cps, cps[1:])]
        steps = [s for s in steps if abs(s) < 100.0]     # ignore the modulo wrap
        if not steps:
            continue
        mn = sorted(steps)[len(steps) // 2]
        moved += 1
        print("  PRN %-3d %3d posts  median step %+0.5f chips  (predicted -0.0375 while railed"
              " at disc +0.6)" % (prn, len(seq), mn))
        if mn > 0:
            fails.append("[2] PRN %d trim is moving the WRONG WAY (median step %+0.5f); disc "
                         "+0.6 must drive the code phase DOWN" % (prn, mn))
        # ⚠️ SIGN ALONE IS NOT ENOUGH -- a gain 100x wrong still points the right way. Check
        # the EARLY steps against the predicted -0.0375, before the integrator converges: with
        # disc pinned at +0.6 the loop walks to a fixed point (gain*tau/leak) and its steps
        # then shrink to ~0, which is why the median over the whole run is small and says
        # nothing about the gain.
        # ⚠️ THE FIRST POSTS ARE THE POLICY CYCLE'S, before the fast loop has been armed by
        # it -- their step is exactly 0 and sampling them measures nothing. Take the first
        # steps that actually MOVE: with disc pinned, those are the loop starting from trim 0
        # and are the only place the gain is observable before convergence damps it.
        early = [x for x in steps if x != 0.0][:5]
        if len(early) >= 3:
            em = sorted(early)[len(early) // 2]
            print("           first %d steps median %+0.5f chips (predicted %+0.5f)"
                  % (len(early), em, -0.0375))
            if not (-0.1125 <= em <= -0.0125):      # predicted +-3x
                fails.append("[2] PRN %d: early step %+0.5f chips is not within 3x of the "
                             "predicted -0.0375 (dll_gain 0.25 x tau -0.15). The loop is "
                             "actuating, but not by the amount the gain says."
                             % (prn, em))
        # [3] consecutive fast POSTs must differ ONLY in code_phase_chips
        for (t1, s1), (t2, s2) in zip(seq, seq[1:]):
            k1, k2 = set(s1), set(s2)
            if k1 != k2:
                fails.append("[3] PRN %d: the seed's FIELD SET changed between posts (%s) -- "
                             "the fast path is rebuilding the payload, which drops what "
                             "policy put there" % (prn, sorted(k1 ^ k2)))
                break
            diff = [k for k in k1 if s1[k] != s2[k] and k != "code_phase_chips"]
            if diff:
                fails.append("[3] PRN %d: fields other than code_phase_chips changed between "
                             "consecutive posts: %s -- an actuator must not overwrite another "
                             "loop's fields" % (prn, sorted(diff)))
                break
    if not moved:
        fails.append("[2] no PRN accumulated enough posts to measure the trim -- the gate "
                     "could not have failed; see %s" % blog)

    print()
    if fails:
        print("FAILED (%d):" % len(fails))
        for f in fails:
            print("  - %s" % f)
        print("\nbroker log: %s\nkotekan log: %s" % (blog, klog))
    else:
        print("PASS -- fast loop actuates at rate, in the right direction, without disturbing "
              "any field it does not own, on exactly the PRNs policy armed")
    if not a.keep and not fails:
        shutil.rmtree(d, ignore_errors=True)
    else:
        print("kept %s" % d)
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
