##########################################
#
# airspy_autocorr.yaml
#
# A quick-and-dirty config to demonstrate the use of the AirSpy
# producer. It gathers data around 1420MHz, channelizes and
# autocorrelates it, then streams to a local listener.
#
# Author: Keith Vanderlinde
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: info

instrument_name: airspy

samples_per_data_set: 32768
bytes_per_sample: 2
buffer_depth: 10
cpu_affinity: [4,5,6,7]
num_elements: 1
one: 1
two: 2
sizeof_float: 4

meta_pool:
  kotekan_metadata_pool: chimeMetadata
  num_metadata_objects: 5 * buffer_depth

input_buf:
  kotekan_buffer: standard
  metadata_pool: meta_pool
  num_frames: buffer_depth
  frame_size: samples_per_data_set * bytes_per_sample

sample_bw: 10. #MHz, must be float?
freq: 1421.    #MHz
airspy_input:
  kotekan_stage: airspyInput
  out_buf: input_buf
  gain_lna: 10 #0-14
  gain_mix: 10 #0-15
  gain_if:  10 #0-15
  biast_power: false

spectrum_output:
  integration_length: 64
  power_integration_length: 64
  spectrum_length: 1024

  post_fengine_buf:
    kotekan_buffer: standard
    metadata_pool: meta_pool
    num_frames: buffer_depth
    frame_size: samples_per_data_set * sizeof_float # * 2 for complex / 2 for half-size

  fengine:
    kotekan_stage: fftwEngine
    in_buf: input_buf
    out_buf: post_fengine_buf

  post_corr_buf:
    kotekan_buffer: standard
    metadata_pool: meta_pool
    num_frames: buffer_depth
    frame_size: ( spectrum_length + one ) * sizeof_float

  xengine:
    kotekan_stage: simpleAutocorr
    in_buf: post_fengine_buf
    out_buf: post_corr_buf

  power_stream:
    kotekan_stage: networkPowerStream
    num_freq: 1024
    samples_per_data_set: 64
    destination_port: 23401
    destination_ip: "127.0.0.1"
    destination_protocol: TCP
    in_buf: post_corr_buf
