##########################################
#
# beam_recv_template.yaml
#
# Starter configuration for extra beam receivers
#
# Author: Andre Renard
#
##########################################
---
type: config
log_level: info
cpu_affinity: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
samples_per_data_set: 49152
num_pol: 2

telescope:
  name: CHIMETelescope
  require_gps: true
  query_gps: true
  require_frequency_map: true
  query_frequency_map: true
  allow_default_frequency_map: false

dataset_manager:
  use_dataset_broker: false

beam_metadata_pool:
  kotekan_metadata_pool: BeamMetadata
  num_metadata_objects: 4096

beam_recv_buffer:
  kotekan_buffer: standard
  num_frames: 2048
  metadata_pool: beam_metadata_pool
  frame_size: samples_per_data_set * num_pol

recv:
  kotekan_stage: bufferRecv
  buf: beam_recv_buffer
  listen_port: 11030
  num_threads: 2

beam_inspect:
  kotekan_stage: BeamInspect
  in_buf: beam_recv_buffer
