---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: info
udp_packet_size: 4928
udp_pulsar_packet_size: 6288
udp_pulsar_header_size: 32
num_links: 4
timesamples_per_packet: 2
timesamples_per_pulsar_packet: 3125
upd_pulsar_packet_in_stream: 16
num_elements: 2048
num_local_freq: 1
num_total_freq: 4
num_pulsar: 10
num_pol: 2
samples_per_data_set: 49152
num_data_sets: 1
buffer_depth: 3
num_gpu_frames: 1
num_gpus: 4
cpu_affinity: [0,1,2,3,4,5,6,7,8,9,10,11]
sizeof_float: 4
num_frb_total_beams: 1024

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 5 * buffer_depth

pulsar_output_buffer:
    num_frames: 4 * buffer_depth
    frame_size: udp_pulsar_packet_size* num_pulsar * num_gpus * upd_pulsar_packet_in_stream
    metadata_pool: main_pool
    kotekan_buffer: standard

simprocess:
  kotekan_stage: pulsarSimProcess
  pulsar_out_buf: pulsar_output_buffer

networkProcess:
  kotekan_stage: pulsarNetworkProcess
  pulsar_out_buf: pulsar_output_buffer
  udp_pulsar_port_number: 1414
  number_of_nodes: 256
  number_of_subnets: 2
  pulsar_node_ips:
    - 10.15.50.10
    - 10.16.50.11
    - 10.15.50.12
    - 10.16.50.13
    - 10.15.50.14
    - 10.16.50.15
