##########################################
#
# chime_science_run_recv_21cm.yaml
#
# CHIME 21cm absorber receiver node configuration used in the December 2019 run.
#
# Author: James Willis
#
##########################################
---
type: config
log_level: info
num_elements: 2048
num_local_freq: 1
udp_packet_size: 4928
num_data_sets: 1
samples_per_data_set: 32768
buffer_depth: 64
num_gpu_frames: 128
block_size: 32
cpu_affinity: [1,6,7,9,14,15]
num_frb_total_beams: 1024
num_sub_freqs: 128

# Constants
sizeof_float: 4

dataset_manager:
  use_dataset_broker: True
  ds_broker_host: "10.1.50.11" # recv1

# Main CHIME Metadata Pool
main_pool:
  kotekan_metadata_pool: chimeMetadata
  num_metadata_objects: 30 * buffer_depth + 5 * baseband_buffer_depth
                        + 100 * 8 * buffer_depth # This part is for the sk/var output.

cpu_hfb_output_buffers:
    num_frames: buffer_depth * 4
    frame_size: num_data_sets * num_sub_freqs * num_frb_total_beams * sizeof_float
    metadata_pool: main_pool
    beamform_hfb_output_buffer_merge:
      kotekan_buffer: standard

# Updatable config blocks
updatable_config:
  flagging:
    kotekan_update_endpoint: "json"
    start_time: 1535048997.
    tag: "initial_flags"
    bad_inputs: [ ]
  gains:
    kotekan_update_endpoint: "json"
    start_time: 1541039597.
    tag: "gain_20181101T023317.440691Z_cyga"

# Kotekan stages
buffer_recv:
  21cm:
    kotekan_stage: bufferRecv
    buf: beamform_hfb_output_buffer_merge
    listen_port: 11027

# Write raw 21cm data
buffer_writers:
  file_length: 256
  root_path: /mnt/recv1/buffer/
  write_ev: True
  file_base: buffer

  21cm:
    kotekan_stage: rawFileWrite
    in_buf: beamform_hfb_output_buffer_merge
    file_name: 'hfb_buf'
    file_ext: 'dump'
    base_dir: '/root/willis/21cm_data'

buffer_status:
  kotekan_stage: bufferStatus
  print_status: false
