#########################################
#
# chime_science_run_recv_baseband.yaml
#
# CHIME baseband receiver node configuration.
#
# Receives baseband dump frames from each GPU node and writes them in a raw
# output file.
#
# Author: Davor Cubranic
#
##########################################
---
type: config
log_level: info
num_elements: 2048
num_local_freq: 1
num_data_sets: 1
samples_per_data_set: 49152
buffer_depth: 64
cpu_affinity: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

# Constants
sizeof_float: 4
sizeof_int: 4
sizeof_short: 2

dataset_manager:
  use_dataset_broker: False
  ds_broker_host: "10.1.50.11" # recv1
  ds_broker_port: 12050

telescope:
  name: CHIMETelescope
  require_gps: false

# Baseband Metadata Pool
baseband_metadata_pool:
  kotekan_metadata_pool: BasebandMetadata
  num_metadata_objects: 65536

basdband_bufs:
  metadata_pool: baseband_metadata_pool
  frame_size: num_elements * samples_per_data_set / 96
  num_frames: 45 * 96
  baseband_recv_buffer_0:
    kotekan_buffer: standard
  baseband_recv_buffer_1:
    kotekan_buffer: standard
  baseband_recv_buffer_2:
    kotekan_buffer: standard
  baseband_recv_buffer_3:
    kotekan_buffer: standard

# Kotekan stages
baseband_recv:
  drop_frames: false
  recv_0:
    kotekan_stage: bufferRecv
    buf: baseband_recv_buffer_0
    listen_port: 11027
  recv_1:
    kotekan_stage: bufferRecv
    buf: baseband_recv_buffer_1
    listen_port: 11028
  recv_2:
    kotekan_stage: bufferRecv
    buf: baseband_recv_buffer_2
    listen_port: 11029
  recv_3:
    kotekan_stage: bufferRecv
    buf: baseband_recv_buffer_3
    listen_port: 11030

write_baseband:
  root_path: /data/baseband_raw/
  dump_timeout: 300
  write_0:
    kotekan_stage: BasebandWriter
    in_buf: baseband_recv_buffer_0
  write_1:
    kotekan_stage: BasebandWriter
    in_buf: baseband_recv_buffer_1
  write_2:
    kotekan_stage: BasebandWriter
    in_buf: baseband_recv_buffer_2
  write_3:
    kotekan_stage: BasebandWriter
    in_buf: baseband_recv_buffer_3


buffer_status:
  kotekan_stage: bufferStatus
  print_status: false
