#!/usr/bin/env python3
"""Generate the CLOSED-LOOP single-kotekan config: search + track in one instance,
driven by the external Python broker. Each sub-band channel feeds BOTH a
GnssChannelCorrelator (search) and a GnssChannelizedTracker (measure):

  F-engine -> GnssSubbandSplit (N channels)
            |-> N GnssChannelCorrelator -> GnssSearchAggregator   (REST detections)
            \\-> N GnssChannelizedTracker -> GnssCoherentCombiner  (REST |A| status)

The trackers start UNSEEDED (code phase/Doppler 0 -> combined |A| ~ noise). The
broker (python/scripts/gps_distributed_broker.py) polls aggregate/get_detections,
forms consensus seeds, and POSTs them to track_NN/set_seeds; the combined |A|
should then jump as every sub-band despreads the same (cp, Doppler) and recombines
coherently. Matches the N=40 @ 20 MSPS geometry of search_dist.yaml.

Output: config/loop_single.yaml.
"""

NCH = 40
PRNS = "[10, 23]"
NWIN = 8
NPRN = 2
ND, MP, HDR = 25, 250, 64
PC_FRAME = HDR + NPRN * NWIN * ND * MP * 8 + MP * 8  # +window-0 raw block for the refine

L = []
L.append("""---
# AUTO-GENERATED by gen_loop_config.py -- closed-loop search+track in one kotekan.
type: config
log_level: warn
instrument_name: airspy_gps
telescope: { name: ICETelescope, num_polarizations: 1, num_dishes: 1 }

samples_per_data_set: 49920
bytes_per_sample: 2
buffer_depth: 16
p_depth: 4
sizeof_float: 4
cpu_affinity: [0, 1, 2, 3]

spectrum_length: %d
num_taps: 4
sample_rate: 20.0e6
f_offset: 5.0e6
signal: GPS_L1CA
n_prn: %d
record_floats: 11
doppler_margin_hz: 900000.0
acquire_snr: 12.0
acquire_windows: %d
doppler_min: -6000.0
doppler_max: 6000.0
doppler_step: 500.0
prns: %s

gnss_pool: { kotekan_metadata_pool: GnssChanMetadata, num_metadata_objects: 6 * buffer_depth }

input_buf: { kotekan_buffer: standard, metadata_pool: none,      num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
chan_buf:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float }
""" % (NCH, NPRN, NWIN, PRNS))

# Each channel: data buffer (two consumers: corr + track), P_c buffer, record buffer.
for c in range(NCH):
    L.append("ch_%02d:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, NCH))
    L.append("pc_%02d:  { kotekan_buffer: standard, metadata_pool: none, num_frames: p_depth, frame_size: %d }" % (c, PC_FRAME))
    L.append("rec_%02d: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }" % c)
L.append("out_buf: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }")
L.append("")

L.append("""read_in: { kotekan_stage: rawFileRead, buf: input_buf, base_dir: "/tmp/gpsin_ref", file_name: "gpsin", file_ext: "raw", end_interrupt: true }
fengine: { kotekan_stage: fftwEngine, in_buf: input_buf, out_buf: chan_buf, input_type: real, pfb_window: hamming }""")

out_bufs = "[" + ", ".join("ch_%02d" % c for c in range(NCH)) + "]"
lo = "[" + ", ".join(str(c) for c in range(NCH)) + "]"
hi = "[" + ", ".join(str(c + 1) for c in range(NCH)) + "]"
L.append("split: { kotekan_stage: GnssSubbandSplit, in_buf: chan_buf, out_bufs: %s, subband_lo: %s, subband_hi: %s }" % (out_bufs, lo, hi))
L.append("")

# Search arm: one correlator per channel -> aggregator.
for c in range(NCH):
    L.append("corr_%02d: { kotekan_stage: GnssChannelCorrelator, in_buf: ch_%02d, out_buf: pc_%02d, channel_offset: %d }" % (c, c, c, c))
agg_in = "[" + ", ".join("pc_%02d" % c for c in range(NCH)) + "]"
L.append("aggregate: { kotekan_stage: GnssSearchAggregator, in_bufs: %s }" % agg_in)
L.append("")

# Track arm: one tracker per channel (UNSEEDED) -> combiner. Same ch_NN buffers
# (second consumer); seeds arrive from the broker via track_NN/set_seeds.
for c in range(NCH):
    L.append("track_%02d: { kotekan_stage: GnssChannelizedTracker, in_buf: ch_%02d, out_buf: rec_%02d, channel_offset: %d, n_channels: 1 }" % (c, c, c, c))
comb_in = "[" + ", ".join("rec_%02d" % c for c in range(NCH)) + "]"
L.append("combiner: { kotekan_stage: GnssCoherentCombiner, in_bufs: %s, out_buf: out_buf }" % comb_in)
L.append("sink: { kotekan_stage: dropAllFrames, in_buf: out_buf }")

open("config/loop_single.yaml", "w").write("\n".join(L) + "\n")
print("wrote config/loop_single.yaml: %d correlators + %d trackers, 1 aggregator, 1 combiner; P_c %.1f MB"
      % (NCH, NCH, PC_FRAME / 1e6))
