#!/usr/bin/env python3
"""Generate a MONOLITHIC live ground-truth config: airspy -> valve -> GpsReplicaCorrelator
-> records. The monolithic correlator is the validated full-band FFT search/track (the same
one the offline configs use); running it live on the airspy tells us the SNR we SHOULD be
getting, independent of the whole channelized (PFB + per-channel + combine) path.

  GNSS_SIGNAL=L1CA   python3 config/gen_mono_config.py   # -> config/live_mono.yaml      (default)
  GNSS_SIGNAL=L2C_CM python3 config/gen_mono_config.py   # -> config/live_mono_l2c.yaml

Use it two ways:
  * L2 ground truth: does the monolithic see L2C at all, and at what SNR? (vs the channelized
    live_l2c.yaml, which currently sees nothing.) If mono detects and channelized doesn't, the
    channelized path still has a bug; if neither, it's a signal/antenna problem.
  * L1 regression check: run on L1 and compare its SNR to the channelized live.yaml. The
    channelized replica fix is a no-op for L1 (comb_mult=1, unit tests pass), so the two
    should agree; if they do, a low L1 SNR is environmental (different sats / elevation / RFI),
    not a code regression.

Run (records land in /tmp/gpsmono; watch SNR with gps_mono_watch.py):
  LAT=43.968697 LON=-79.252106 ALT=260 ./config/run_mono.sh           # L1
  GNSS_SIGNAL=L2C_CM LAT=.. LON=.. ./config/run_mono.sh               # L2C

A VALVE decouples the airspy so the (heavy) monolithic never backpressures it -- when the
correlator can't keep up, whole frames drop cleanly. samples_per_data_set = 100000 (20 ms)
so every airspy frame holds a full L2C code period (or 20 L1 periods); a valve drop never
splits a correlation block.
"""
import os

# sbw = airspy device sample_bw (MHz): 2.5 -> 5 MSPS real (L1/L2); 10 -> 20 MSPS real (L5, 10.23
# Mcps). Fs = 2*sbw*1e6, f_offset = Fs/4 derived below. samples_per_data_set 100000 is a whole
# number of code blocks for all three (20 L1 / 1 L2C / 5 L5 blocks). L5 targets the Q5 pilot.
SIGNALS = {
    "L1CA":   dict(name="GPS_L1CA",   freq=1575.42, dstep=500.0, inc=100, lock=12.0, sbw=2.5,
                   out="live_mono.yaml",     base="/tmp/gpsmono"),
    "L2C_CM": dict(name="GPS_L2C_CM", freq=1227.6,  dstep=50.0,  inc=10,  lock=8.0,  sbw=2.5,
                   out="live_mono_l2c.yaml", base="/tmp/gpsmono"),
    "L5_Q":   dict(name="GPS_L5_Q",   freq=1176.45, dstep=500.0, inc=100, lock=12.0, sbw=10.0,
                   out="live_mono_l5.yaml",  base="/tmp/gpsmono"),
}
SIG = os.environ.get("GNSS_SIGNAL", "L1CA")
if SIG not in SIGNALS:
    raise SystemExit("GNSS_SIGNAL must be one of %s (got %r)" % (list(SIGNALS), SIG))
S = SIGNALS[SIG]
FS = 2.0 * S["sbw"] * 1e6
FS_STR = "%se6" % (FS / 1e6)          # keep the '.e6' form: YAML get<double> stod-coerces it
FOFF_STR = "%se6" % (FS / 4.0 / 1e6)

cfg = """---
# AUTO-GENERATED by gen_mono_config.py (GNSS_SIGNAL=%s) -- monolithic ground-truth:
# airspy -> valve -> GpsReplicaCorrelator (full-band FFT search/track) -> records.
# Watch SNR: python3 python/scripts/gps_mono_watch.py
type: config
log_level: info
instrument_name: airspy_gps
telescope: { name: ICETelescope, num_polarizations: 1, num_dishes: 1 }

samples_per_data_set: 100000     # whole code blocks: 20 L1 / 1 L2C @ 5 MSPS, 5 L5 @ 20 MSPS
bytes_per_sample: 2
buffer_depth: 16
sizeof_float: 4
cpu_affinity: [0, 1, 2, 3, 4, 5, 6, 7]

n_prn: 11
record_floats: 11
# run_live-style: run_mono.sh auto-patches prns:/n_prn: to the visible set.
prns: [28, 32, 31, 25, 3, 10, 26, 1, 12, 13, 2]

# GNSS metadata pool so the airspy stamps fpga_seq on input_buf (and the valve can copy it to
# input_buf2). Without this the valve fails -- it has no metadata to copy from a bare buffer.
gnss_pool: { kotekan_metadata_pool: GnssChanMetadata, num_metadata_objects: 4 * buffer_depth }
input_buf:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
input_buf2: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
rec_buf:    { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }

airspy_in:
    kotekan_stage: airspyInput
    out_buf: input_buf
    freq: %g
    sample_bw: %g
    gain_lna: 14
    gain_mix: 15
    gain_if: 15
    biast_power: true
# Valve: drop whole 20 ms frames cleanly if the heavy correlator falls behind, so the airspy
# never backpressures (each surviving frame is internally contiguous -> blocks stay valid).
valve: { kotekan_stage: Valve, in_buf: input_buf, out_buf: input_buf2 }
gps_correlator:
    kotekan_stage: GpsReplicaCorrelator
    in_buf: input_buf2
    out_buf: rec_buf
    signal: %s
    sample_rate: %s
    f_offset: %s
    doppler_min: -6000.0
    doppler_max: 6000.0
    doppler_step: %g
    incoherent_ms: %d
    lock_snr: %g
    track_phase: false
record: { kotekan_stage: rawFileWrite, in_buf: rec_buf, base_dir: "%s", file_name: "mono", file_ext: "raw", prefix_hostname: false, num_frames_per_file: 1000000, exit_after_n_files: 1000000 }
""" % (SIG, S["freq"], S["sbw"], S["name"], FS_STR, FOFF_STR, S["dstep"], S["inc"], S["lock"],
       S["base"])

open("config/" + S["out"], "w").write(cfg)
print("wrote config/%s: airspy @ %g MHz -> valve -> GpsReplicaCorrelator(%s, dstep %g, inc %d) -> %s"
      % (S["out"], S["freq"], S["name"], S["dstep"], S["inc"], S["base"]))
