#!/usr/bin/env python3
"""Generate the UNIFIED (centralized) search config: ship the covering channels'
raw channelized voltage -- the *small* search data, not the expanded P_c surface
(see docs/gnss_distributed_search_scaling.md) -- to one search node and run the
existing GnssChannelizedSearch (coarse + refine) there.

  F-engine -> GnssSubbandSplit (covering channels only)
            -> [bufferSend -> bufferRecv]*   (one per channel; the CHORD comb
                 scatters covering channels across nodes, each ships its one)
            -> GnssChannelGather ([hop][n_cov] buffer)
            -> GnssChannelizedSearch (channel_offset = first covering channel)

For the validation geometry (N=40 @ 20 MSPS, f_offset 5 MHz, GPS L1CA) the
covering set is channels 12..28 (17 channels; half_bandwidth = chip_rate +
doppler_margin). Two modes:
  python gen_unified_config.py            # full bufferSend/Recv transport
  python gen_unified_config.py --local    # gather reads channels directly (no net)

Output: config/search_unified.yaml.
"""
import sys

LOCAL = "--local" in sys.argv
N = 40
COV = list(range(12, 29))     # covering channels 12..28 (17)
NCOV = len(COV)
PRNS = "[5, 10, 23]"
PORT0 = 15001

L = []
L.append("""---
# AUTO-GENERATED by gen_unified_config.py -- unified (centralized) search.
# Mode: %s
type: config
log_level: info
instrument_name: airspy_gps
telescope: { name: ICETelescope, num_polarizations: 1, num_dishes: 1 }

samples_per_data_set: 49920
bytes_per_sample: 2
buffer_depth: 16
sizeof_float: 4
cpu_affinity: [0, 1, 2, 3]

spectrum_length: %d
num_taps: 4
sample_rate: 20.0e6
f_offset: 5.0e6
signal: GPS_L1CA

gnss_pool: { kotekan_metadata_pool: GnssChanMetadata, num_metadata_objects: 64 * buffer_depth }

input_buf: { kotekan_buffer: standard, metadata_pool: none,      num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
chan_buf:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float }
""" % ("local (no transport)" if LOCAL else "bufferSend/Recv transport", N))

# Per covering channel: split output ch_c, and (transport mode) a recv buffer rc_c.
for c in COV:
    L.append("ch_%02d: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, N))
    if not LOCAL:
        L.append("rc_%02d: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, N))
# Gathered multi-channel buffer: [hop][n_cov].
L.append("gather_buf: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d * %d }" % (N, NCOV))
L.append("")

# end_interrupt false: with the send/recv transport in-flight, let the pipeline
# drain rather than shut down the instant the file ends (poll detections over REST).
L.append("""read_in: { kotekan_stage: rawFileRead, buf: input_buf, base_dir: "/tmp/gpsin_ref", file_name: "gpsin", file_ext: "raw", end_interrupt: false }
fengine: { kotekan_stage: fftwEngine, in_buf: input_buf, out_buf: chan_buf, input_type: real, pfb_window: hamming }""")

# Split out ONLY the covering channels (one single-channel buffer each).
out_bufs = "[" + ", ".join("ch_%02d" % c for c in COV) + "]"
lo = "[" + ", ".join(str(c) for c in COV) + "]"
hi = "[" + ", ".join(str(c + 1) for c in COV) + "]"
L.append("split: { kotekan_stage: GnssSubbandSplit, in_buf: chan_buf, out_bufs: %s, subband_lo: %s, subband_hi: %s }" % (out_bufs, lo, hi))
L.append("")

if LOCAL:
    gather_in = "[" + ", ".join("ch_%02d" % c for c in COV) + "]"
else:
    # One send/recv pair per covering channel (each "node" ships its one channel).
    for i, c in enumerate(COV):
        L.append("send_%02d: { kotekan_stage: bufferSend, buf: ch_%02d, server_ip: 127.0.0.1, server_port: %d, drop_frames: false }" % (c, c, PORT0 + i))
        L.append("recv_%02d: { kotekan_stage: bufferRecv, buf: rc_%02d, listen_port: %d, num_threads: 1 }" % (c, c, PORT0 + i))
    gather_in = "[" + ", ".join("rc_%02d" % c for c in COV) + "]"
    L.append("")

L.append("gather: { kotekan_stage: GnssChannelGather, in_bufs: %s, out_buf: gather_buf }" % gather_in)
L.append("")

# The existing monolithic search runs on the gathered covering channels.
L.append("""search:
    kotekan_stage: GnssChannelizedSearch
    in_buf: gather_buf
    channel_offset: %d
    n_channels: %d
    signal: GPS_L1CA
    doppler_margin_hz: 900000.0
    acquire_snr: 12.0
    acquire_windows: 10
    hops_per_record: 250
    doppler_min: -6000.0
    doppler_max: 6000.0
    doppler_step: 500.0
    prns: %s""" % (COV[0], NCOV, PRNS))

open("config/search_unified.yaml", "w").write("\n".join(L) + "\n")
print("wrote config/search_unified.yaml (%s): %d covering channels %d..%d -> gather -> search"
      % ("LOCAL" if LOCAL else "TRANSPORT", NCOV, COV[0], COV[-1]))
