#!/usr/bin/env python3
"""Generate the single-kotekan DISTRIBUTED SEARCH config: F-engine -> fan out ALL
N channels into independent single-sub-band streams -> N GnssChannelCorrelator
(each ships its per-channel P_c surface) -> 1 GnssSearchAggregator (cross-channel
combine + peak + REST detections). This is the search counterpart of the comb
(gen_comb_config.py): the aggregator's surface is bit-identical to a monolithic
full-band GnssChannelizedSearch, so its detections must match the known seeds
(PRN 10: dop -1250, cp ~647; PRN 23: dop -2750, cp ~747.5).

Matches airspy_gps_search_validate.yaml's F-engine geometry (N=40 @ 20 MSPS).
Output: config/search_dist.yaml.
"""

NCH = 40
PRNS = "[5, 10, 23]"     # 1 control (5) + 2 known (10, 23)
NWIN = 8                 # integration windows per snapshot (P_c payload scales with this)
NPRN = 3

# P_c payload per covering frame: n_prn * nwin * nd * Mp complex<float>.
# nd = 25 (doppler -6000..6000 step 500), Mp = 250 (code_samples 20000 / gcd(80,20000)).
ND, MP, HDR = 25, 250, 64
PAY = NPRN * NWIN * ND * MP * 8
FRAME = HDR + PAY

L = []
L.append("""---
# AUTO-GENERATED by gen_search_config.py -- single-kotekan distributed search.
type: config
log_level: info
instrument_name: airspy_gps
telescope: { name: ICETelescope, num_polarizations: 1, num_dishes: 1 }

samples_per_data_set: 49920
bytes_per_sample: 2
buffer_depth: 16
p_depth: 4
sizeof_float: 4
cpu_affinity: [0, 1, 2, 3]

spectrum_length: %d
num_taps: 4
sample_rate: 20.0e6
f_offset: 5.0e6
signal: GPS_L1CA
doppler_margin_hz: 900000.0
acquire_snr: 12.0
acquire_windows: %d
doppler_min: -6000.0
doppler_max: 6000.0
doppler_step: 500.0
prns: %s

gnss_pool: { kotekan_metadata_pool: GnssChanMetadata, num_metadata_objects: 4 * buffer_depth }

input_buf: { kotekan_buffer: standard, metadata_pool: none,      num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
chan_buf:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float }
""" % (NCH, NWIN, PRNS))

# Per-channel data buffers (one sub-band each) + P_c surface buffers.
for c in range(NCH):
    L.append("ch_%02d: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, NCH))
    L.append("pc_%02d: { kotekan_buffer: standard, metadata_pool: none, num_frames: p_depth, frame_size: %d }" % (c, FRAME))
L.append("")

L.append("""read_in: { kotekan_stage: rawFileRead, buf: input_buf, base_dir: "/tmp/gpsin_ref", file_name: "gpsin", file_ext: "raw", end_interrupt: true }
fengine: { kotekan_stage: fftwEngine, in_buf: input_buf, out_buf: chan_buf, input_type: real, pfb_window: hamming }""")

out_bufs = "[" + ", ".join("ch_%02d" % c for c in range(NCH)) + "]"
lo = "[" + ", ".join(str(c) for c in range(NCH)) + "]"
hi = "[" + ", ".join(str(c + 1) for c in range(NCH)) + "]"
L.append("split: { kotekan_stage: GnssSubbandSplit, in_buf: chan_buf, out_bufs: %s, subband_lo: %s, subband_hi: %s }" % (out_bufs, lo, hi))
L.append("")

# One correlator per channel (channel_offset = c). Non-covering channels emit
# cheap header-only P_c frames; covering ones ship the surface.
for c in range(NCH):
    L.append("corr_%02d: { kotekan_stage: GnssChannelCorrelator, in_buf: ch_%02d, out_buf: pc_%02d, channel_offset: %d }" % (c, c, c, c))
L.append("")

in_bufs = "[" + ", ".join("pc_%02d" % c for c in range(NCH)) + "]"
L.append("aggregate: { kotekan_stage: GnssSearchAggregator, in_bufs: %s }" % in_bufs)

open("config/search_dist.yaml", "w").write("\n".join(L) + "\n")
print("wrote config/search_dist.yaml: %d correlators, 1 aggregator; P_c frame %d B (%.1f MB)"
      % (NCH, FRAME, FRAME / 1e6))
