#!/usr/bin/env python3
"""Generate the FULL LIVE pipeline off the airspy: the whole CHORD-mirror chain,
end to end, in one kotekan, driven by the external broker.

  airspyInput -> fftwEngine (PFB) -> GnssSubbandSplit (N channels)
    search arm:  covering ch -> bufferSend -> bufferRecv -> GnssChannelGather
                 -> GnssChannelizedSearch                     (REST detections)
    track  arm:  covering ch -> GnssChannelizedTracker -> GnssCoherentCombiner
                 -> rawFileWrite (recorded signal level |A| vs time)
  broker (python --detectors search) closes the loop: detections -> set_seeds.

Airspy in RAW mode at the 10 MSPS device setting streams the 20 MSPS real ADC
(carrier at Fs/4 = 5 MHz = f_offset); biast_power on for the active antenna. A
live stream is realtime-paced by the hardware, so the wall-clock broker keeps up
with code-Doppler drift natively (no frame_period_us needed).

Trackers run only on the covering channels (12..28) -- the others carry no carrier
power and would just burn cycles. Output: config/live_full.yaml.
"""

N = 40
COV = list(range(12, 29))     # covering channels 12..28 (17)
NCOV = len(COV)
PRNS = "[%s]" % ", ".join(str(p) for p in range(1,33))
NPRN = 32
PORT0 = 15001

L = []
L.append("""---
# AUTO-GENERATED by gen_live_config.py -- full live airspy pipeline.
type: config
log_level: info
instrument_name: airspy_gps
telescope: { name: ICETelescope, num_polarizations: 1, num_dishes: 1 }

# Allow the browser power-waterfall viewer (served on :8080) to query the REST API.
rest_server:
    cors_allow_origins: ["http://localhost:8080", "http://127.0.0.1:8080"]

samples_per_data_set: 49920
bytes_per_sample: 2
buffer_depth: 16
sizeof_float: 4
cpu_affinity: [0, 1, 2, 3, 4, 5, 6, 7]

spectrum_length: %d
num_taps: 4
sample_rate: 20.0e6
f_offset: 5.0e6
signal: GPS_L1CA
code_doppler_sign: 1.0   # flip to -1.0 if high-Doppler sats still won't lock
n_prn: %d
record_floats: 11
doppler_margin_hz: 900000.0
acquire_snr: 6.0
acquire_windows: 30
doppler_min: -6000.0
doppler_max: 6000.0
doppler_step: 500.0
prns: %s

gnss_pool: { kotekan_metadata_pool: GnssChanMetadata, num_metadata_objects: 32 * buffer_depth }

input_buf: { kotekan_buffer: standard, metadata_pool: none,      num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
chan_buf:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float }
""" % (N, NPRN, PRNS))

for c in range(N):
    L.append("ch_%02d: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, N))
for c in COV:
    L.append("rc_%02d:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, N))
    L.append("rec_%02d: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }" % c)
L.append("gather_buf: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d * %d }" % (N, NCOV))
L.append("out_buf: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }")
L.append("")

# Live front end: airspy at L1, 10 MSPS device mode -> 20 MSPS RAW, bias-tee on.
L.append("""airspy_in:
    kotekan_stage: airspyInput
    out_buf: input_buf
    freq: 1575.42
    sample_bw: 10
    gain_lna: 14
    gain_mix: 15
    gain_if: 15
    biast_power: true
fengine: { kotekan_stage: fftwEngine, in_buf: input_buf, out_buf: chan_buf, input_type: real, pfb_window: hamming }""")

out_bufs = "[" + ", ".join("ch_%02d" % c for c in range(N)) + "]"
lo = "[" + ", ".join(str(c) for c in range(N)) + "]"
hi = "[" + ", ".join(str(c + 1) for c in range(N)) + "]"
L.append("split: { kotekan_stage: GnssSubbandSplit, in_buf: chan_buf, out_bufs: %s, subband_lo: %s, subband_hi: %s }" % (out_bufs, lo, hi))
L.append("")

# Search arm: transmit covering channels -> gather -> search.
for i, c in enumerate(COV):
    L.append("send_%02d: { kotekan_stage: bufferSend, buf: ch_%02d, server_ip: 127.0.0.1, server_port: %d, drop_frames: false }" % (c, c, PORT0 + i))
    L.append("recv_%02d: { kotekan_stage: bufferRecv, buf: rc_%02d, listen_port: %d, num_threads: 1 }" % (c, c, PORT0 + i))
gather_in = "[" + ", ".join("rc_%02d" % c for c in COV) + "]"
L.append("gather: { kotekan_stage: GnssChannelGather, in_bufs: %s, out_buf: gather_buf }" % gather_in)
L.append("search: { kotekan_stage: GnssChannelizedSearch, in_buf: gather_buf, channel_offset: %d, n_channels: %d, acquire_snr: 6.0, acquire_windows: 30 }" % (COV[0], NCOV))
L.append("")

# Track arm: trackers on covering channels (UNSEEDED) -> combiner -> record.
for c in COV:
    L.append("track_%02d: { kotekan_stage: GnssChannelizedTracker, in_buf: ch_%02d, out_buf: rec_%02d, channel_offset: %d, n_channels: 1 }" % (c, c, c, c))
comb_in = "[" + ", ".join("rec_%02d" % c for c in COV) + "]"
L.append("combiner: { kotekan_stage: GnssCoherentCombiner, in_bufs: %s, out_buf: out_buf, integration_length: 10 }" % comb_in)
L.append('record: { kotekan_stage: rawFileWrite, in_buf: out_buf, base_dir: "/tmp/gpslive", file_name: "level", file_ext: "raw", prefix_hostname: false, num_frames_per_file: 1000000, exit_after_n_files: 1000000 }')
L.append("")

# Diagnostic spectrum path: a second, FINE F-engine (1248 ch = 8 kHz/bin over the
# 10 MHz band; fft_len 2496 divides the 49920-sample frame at 20 hops) taps the
# shared airspy input_buf -> simpleAutocorr (voltages -> power) -> networkPowerStream
# (TCP :23401) -> SpawnProcess (browser waterfall + ADC stats). Independent of the
# GNSS pipeline; lets you watch for RFI / compression / oscillations live.
# Viewer in a browser at http://localhost:8080 (needs twisted+autobahn -- set
# VIEWER_PYTHON to that venv). spectrum_length is scoped local so the GNSS F-engine
# keeps its N=40.
L.append("""diag:
    spectrum_length: 1248
    integration_length: 64
    power_integration_length: 64

    post_fengine_diag: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float }
    fengine_diag: { kotekan_stage: fftwEngine, input_type: real, num_taps: 4, pfb_window: hamming, in_buf: input_buf, out_buf: post_fengine_diag }

    post_corr_diag: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: ( spectrum_length + 1 ) * sizeof_float }
    autocorr: { kotekan_stage: simpleAutocorr, in_buf: post_fengine_diag, out_buf: post_corr_diag }

    power_stream: { kotekan_stage: networkPowerStream, num_freq: 1248, num_elements: 1, samples_per_data_set: 64, power_integration_length: 64, freq: 1575.42, sample_bw: 10, destination_port: 23401, destination_ip: "127.0.0.1", destination_protocol: TCP, in_buf: post_corr_diag }
    spawn_pyviewer: { kotekan_stage: SpawnProcess, in_buf: post_corr_diag, exec: '${VIEWER_PYTHON:-python3} python/scripts/js_viewer/livebeam_server.py' }""")

open("config/live_full.yaml", "w").write("\n".join(L) + "\n")
print("wrote config/live_full.yaml: airspy -> PFB -> split -> %dx send/recv -> gather -> search; %d trackers -> combiner -> record"
      % (NCOV, NCOV))
print("broker: python python/scripts/gps_distributed_broker.py --detectors search --trackers 'track_{12..28}' --combiner combiner --acquire-snr 10 --interval 0.2")
