#!/usr/bin/env python3
"""Generate the CLOSED-LOOP single-kotekan config: search + track in one instance,
driven by the external Python broker. The search runs on the UNIFIED (variant B)
path -- gather the covering channels' voltage and run the monolithic
GnssChannelizedSearch -- not the retired combed-P_c path.

  F-engine -> GnssSubbandSplit (N channels)
            |-> GnssChannelGather (covering chans) -> GnssChannelizedSearch  (REST detections)
            \\-> N GnssChannelizedTracker -> GnssCoherentCombiner            (REST |A| status)

The trackers start UNSEEDED (code phase/Doppler 0 -> combined |A| ~ noise). The
broker (python/scripts/gps_distributed_broker.py --detectors search) polls
search/get_detections, forms consensus seeds, and POSTs them to track_NN/set_seeds;
the combined |A| then jumps as every sub-band despreads the same (cp, Doppler) and
recombines coherently. N=40 @ 20 MSPS; covering channels 12..28 (GPS L1CA).

Output: config/loop_single.yaml.
"""

import sys
TRANSPORT = "--transport" in sys.argv  # insert bufferSend/Recv before the gather
                                       # (mirrors the live config, to repro its bug)
PORT0 = 15001
NCH = 40
COV = list(range(12, 29))     # covering channels 12..28 (17), the search gather set
NCOV = len(COV)
PRNS = "[10, 23]"
SPRNS = "[5, 10, 23]"         # search adds a control PRN (5)

L = []
L.append("""---
# AUTO-GENERATED by gen_loop_config.py -- closed-loop search+track in one kotekan.
type: config
log_level: warn
instrument_name: airspy_gps
telescope: { name: ICETelescope, num_polarizations: 1, num_dishes: 1 }

samples_per_data_set: 49920
bytes_per_sample: 2
buffer_depth: 16
sizeof_float: 4
cpu_affinity: [0, 1, 2, 3]

spectrum_length: %d
num_taps: 4
sample_rate: 20.0e6
f_offset: 5.0e6
signal: GPS_L1CA
n_prn: 2
record_floats: 11
doppler_margin_hz: 900000.0
acquire_snr: 12.0
acquire_windows: 10
doppler_min: -6000.0
doppler_max: 6000.0
doppler_step: 500.0
prns: %s

gnss_pool: { kotekan_metadata_pool: GnssChanMetadata, num_metadata_objects: 16 * buffer_depth }

input_buf: { kotekan_buffer: standard, metadata_pool: none,      num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
chan_buf:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float }
""" % (NCH, PRNS))

# Each channel: data buffer (covering ones have two consumers: gather + track),
# plus a per-channel record buffer.
for c in range(NCH):
    L.append("ch_%02d:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, NCH))
    L.append("rec_%02d: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }" % c)
if TRANSPORT:
    for c in COV:
        L.append("rc_%02d:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, NCH))
L.append("gather_buf: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d * %d }" % (NCH, NCOV))
L.append("out_buf: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }")
L.append("")

# Realtime-paced replay (2496 us/frame @ 20 MSPS, end_interrupt false) so the
# wall-clock broker can re-seed faster than code-Doppler drift; without pacing the
# 3 s capture blasts through in <1 s and the loop never locks (test artifact, not
# a pipeline limit). Drop frame_period_us for a live airspy (it paces itself).
L.append("""read_in: { kotekan_stage: rawFileRead, buf: input_buf, base_dir: "/tmp/gpsin_ref", file_name: "gpsin", file_ext: "raw", end_interrupt: false, frame_period_us: 2496 }
fengine: { kotekan_stage: fftwEngine, in_buf: input_buf, out_buf: chan_buf, input_type: real, pfb_window: hamming }""")

out_bufs = "[" + ", ".join("ch_%02d" % c for c in range(NCH)) + "]"
lo = "[" + ", ".join(str(c) for c in range(NCH)) + "]"
hi = "[" + ", ".join(str(c + 1) for c in range(NCH)) + "]"
L.append("split: { kotekan_stage: GnssSubbandSplit, in_buf: chan_buf, out_bufs: %s, subband_lo: %s, subband_hi: %s }" % (out_bufs, lo, hi))
L.append("")

# Search arm (variant B): gather the covering channels -> monolithic search.
# --transport inserts a bufferSend/Recv per covering channel before the gather,
# mirroring the live config (to reproduce/debug its no-lock).
if TRANSPORT:
    for i, c in enumerate(COV):
        L.append("send_%02d: { kotekan_stage: bufferSend, buf: ch_%02d, server_ip: 127.0.0.1, server_port: %d, drop_frames: false }" % (c, c, PORT0 + i))
        L.append("recv_%02d: { kotekan_stage: bufferRecv, buf: rc_%02d, listen_port: %d, num_threads: 1 }" % (c, c, PORT0 + i))
    gather_in = "[" + ", ".join("rc_%02d" % c for c in COV) + "]"
else:
    gather_in = "[" + ", ".join("ch_%02d" % c for c in COV) + "]"
L.append("gather: { kotekan_stage: GnssChannelGather, in_bufs: %s, out_buf: gather_buf }" % gather_in)
L.append("""search:
    kotekan_stage: GnssChannelizedSearch
    in_buf: gather_buf
    channel_offset: %d
    n_channels: %d
    acquire_snr: 12.0
    acquire_windows: 10
    prns: %s""" % (COV[0], NCOV, SPRNS))
L.append("")

# Track arm: one tracker per channel (UNSEEDED) -> combiner. Covering ch_NN buffers
# have a second consumer (the gather); seeds arrive from the broker via set_seeds.
for c in range(NCH):
    L.append("track_%02d: { kotekan_stage: GnssChannelizedTracker, in_buf: ch_%02d, out_buf: rec_%02d, channel_offset: %d, n_channels: 1 }" % (c, c, c, c))
comb_in = "[" + ", ".join("rec_%02d" % c for c in range(NCH)) + "]"
L.append("combiner: { kotekan_stage: GnssCoherentCombiner, in_bufs: %s, out_buf: out_buf }" % comb_in)
# The combiner's out_buf is the SNR tap: one record/PRN per window, carrying the
# coherent-combine amplitude |A| (rec[3], also rec[6] as the SNR proxy) + dop/cp.
# rawFileWrite logs it; swap to dropAllFrames if you only want the REST poll.
L.append('record: { kotekan_stage: rawFileWrite, in_buf: out_buf, base_dir: "/tmp/gpsloop", file_name: "snr", file_ext: "raw", prefix_hostname: false, num_frames_per_file: 100000, exit_after_n_files: 100000 }')

_out = "config/loop_transport.yaml" if TRANSPORT else "config/loop_single.yaml"
open(_out, "w").write("\n".join(L) + "\n")
print("wrote %s: %sgather(%d covering) -> search, %d trackers, 1 combiner"
      % (_out, "%dx send/recv -> " % NCOV if TRANSPORT else "", NCOV, NCH))
