#!/usr/bin/env python3
"""Merge the three per-band GPU configs into ONE kotekan instance: the CHORD-like node.

    python3 config/gen_3band_config.py            -> config/live_3band.yaml

WHY AN INSTANCE MERGE (and not a buffer merge): nothing crosses frequency -- no product is ever
formed between two airspys' samples -- so the merge is at the process level: one kotekan, one
GPU, one REST server, per-band chains side by side. Each band keeps its OWN absolute-time
anchor (its airspy's sample 0 + capture_utc0): the three units share one GPSDO (dither off), so
the inter-band offsets are CONSTANT and the per-band sky clock solves absorb them -- this
in-process set of per-band anchors IS the per-freq-group anchor table, with CHORD the degenerate
one-group case (same master clock AND aligned sample 0).

MECHANICS. Per band (l1 / l2c / l5), from the validated single-band config:
  * prefix every stage + buffer name with '<band>_' (kotekan REST endpoints derive from stage
    unique_names, so duplicates would collide fatally in one process);
  * prefix gpu_mem names (the cudaDeviceInterface registry is GLOBAL per GPU -- L1's and L5's
    'gnss_chan_frame' are different sizes and would trample each other, the exact failure mode
    the ring-name namespacing note in cudaGnssTrack.cpp records);
  * prefix REST seed endpoints ('/l1_gps_track/set_seeds');
  * push the band's top-level scalars (sample_rate, spectrum_length, ...) DOWN into every stage
    block -- the merged file cannot hold three different top-level sample_rates, and kotekan's
    up-tree config lookup makes stage-local keys win;
  * rewrite buffer frame_size expressions numerically (they reference top-level vars);
  * point every spawned viewer at the single REST port.
Top-level: one rest_server (CORS = union), one metadata pool per band (prefixed), shared
log_level/cpu_affinity.
"""
import re
import sys

BANDS = [("l1", "live_l1_dual20.yaml"), ("l2c", "live_l2c_gpu.yaml"), ("l5", "live_l5_gpu.yaml")]
PORT = 12048  # the ONE kotekan REST port; viewers + brokers all talk to it
HERE = "config/"

# Top-level scalar keys that stages/buffers inherit up-tree; pushed down per band.
INHERIT = ["samples_per_data_set", "bytes_per_sample", "buffer_depth", "sizeof_float",
           "spectrum_length", "num_taps", "sample_rate", "f_offset", "signal",
           "code_doppler_sign", "n_prn", "record_floats", "doppler_margin_hz", "acquire_snr",
           "acquire_windows", "doppler_min", "doppler_max", "doppler_step", "prns", "gal_n_prn",
           "bds_n_prn"]
# Keys emitted once, from the first band.
SHARED = ["type", "log_level", "instrument_name", "telescope", "cpu_affinity", "clock_profile"]


def parse_blocks(text):
    """Split a config into (key, block_text) at column-0 keys, preserving order + comments."""
    blocks, cur_key, cur = [], None, []
    for line in text.splitlines():
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):", line)
        if m:
            if cur_key is not None:
                blocks.append((cur_key, "\n".join(cur)))
            cur_key, cur = m.group(1), [line]
        elif cur_key is not None:
            cur.append(line)
        # pre-first-key comments dropped (the merged header replaces them)
    if cur_key is not None:
        blocks.append((cur_key, "\n".join(cur)))
    return blocks


def scalar_value(blocks, key):
    for k, b in blocks:
        if k == key:
            return b.split(":", 1)[1].split("#")[0].strip()
    return None


def main():
    out = ["---",
           "# AUTO-GENERATED by gen_3band_config.py -- DO NOT EDIT. Regenerate instead.",
           "# ONE kotekan, THREE bands (7 constellation chains): the CHORD-like node. Launch via",
           "# config/run_3band.sh. Per-band anchors are independent (shared GPSDO -> constant",
           "# inter-band offsets, absorbed by each band's sky clock solve).", ""]
    shared_done = set()
    cors = set()
    for band, fname in BANDS:
        text = open(HERE + fname).read()
        blocks = parse_blocks(text)
        # names to prefix = every column-0 key that is a stage or buffer (i.e. not in
        # INHERIT/SHARED and not rest_server/gnss_pool -- pool gets prefixed too).
        inherit_vals = {k: scalar_value(blocks, k) for k in INHERIT
                        if scalar_value(blocks, k) is not None}
        names = [k for k, _ in blocks
                 if k not in INHERIT and k not in SHARED and k != "rest_server"]
        out.append(f"# ================= band {band} ({fname}) =================")
        for key, block in blocks:
            if key == "rest_server":
                for m in re.finditer(r'"(http[^"]+)"', block):
                    cors.add(m.group(1))
                continue
            if key in SHARED:
                if key not in shared_done:
                    out.append(block)
                    shared_done.add(key)
                continue
            if key in INHERIT:
                continue  # pushed down instead
            b = block
            # numeric rewrite of the inherited vars inside EXPRESSIONS only -- never at key
            # positions (lookahead excludes "name:"), so "acquire_snr: 10.0" keeps its key while
            # "frame_size: samples_per_data_set / 2" gets its value substituted.
            for k, v in inherit_vals.items():
                b = re.sub(rf"\b{k}\b(?!\s*:)", v, b)
            # prefix stage/buffer REFERENCES (values), never parameter keys: "out_buf" is both a
            # buffer name and a stage parameter key -- the lookahead spares "out_buf:" while
            # prefixing "out_buf: chan_buf2"'s value. The block's OWN key (line 0) is prefixed
            # explicitly below.
            for n in sorted(names, key=len, reverse=True):
                b = re.sub(rf"\b{n}\b(?!\s*:)", f"{band}_{n}", b)
            b = re.sub(rf"^{key}:", f"{band}_{key}:", b, count=1)
            # gpu_mem + seed endpoints
            b = re.sub(r"(gpu_mem[a-z_]*:\s*)([a-z_]+)", rf"\1{band}_\2", b)
            # collapse pure-arithmetic expressions left by the substitution ("199680 / 2"):
            # kotekan's evaluator handles var expressions but a buffer whose size fails to
            # parse is silently not created ("buffer doesn't exist" at stage construction).
            def _ev(m):
                try:
                    return str(int(eval(m.group(1))))
                except Exception:
                    return m.group(0)
            b = re.sub(r"(?<=: )([0-9][0-9 +*/()-]*[0-9])(?=\s*[,}#\n])", _ev, b)
            # cudaProcess in_buffers/out_buffers are {LOCAL_ALIAS: global_name}, and the
            # sub-commands (cudaInputData in_buf:) address the LOCAL alias -- so the alias must
            # be prefixed identically to the global name (the single-band configs used the same
            # word on both sides, which is why the direction was invisible there).
            b = "\n".join(
                re.sub(rf"([{{,]\s*)([a-z0-9_]+):\s*({band}_\2)\b", r"\1\3: \3", ln)
                if re.search(r"\b(in|out)_buffers:", ln) else ln
                for ln in b.splitlines())
            # endpoints referencing a NAMED stage were already prefixed by the name pass;
            # only prefix paths that still lack the band tag (e.g. "/gps_track/...").
            b = re.sub(rf'(seed_endpoint:\s*"/)(?!{band}_)', rf"\g<1>{band}_", b)
            # viewers: all point at the single REST port, and poll band-prefixed stages
            # (some band configs omit --kotekan-rest-port and rely on its default -> append)
            b = re.sub(r"--kotekan-rest-port \d+",
                       f"--kotekan-rest-port {PORT} --stage-prefix {band}_", b)
            b = re.sub(r"(livebeam_server\.py(?:(?!--stage-prefix)[^'])*)'",
                       rf"\1 --kotekan-rest-port {PORT} --stage-prefix {band}_'", b)
            # push down the inherited scalars into stage blocks (dict-style stages get them
            # appended as an indented block; flow-style {..} stages get them injected)
            first = b.splitlines()[0]
            is_stage = "kotekan_stage" in b or "cudaProcess" in b
            if is_stage:
                # never push a key the stage already sets AT ITS OWN LEVEL (duplicate yaml
                # keys) -- but keys inside NESTED blocks (cudaProcess commands set their own
                # prns/signal) must NOT suppress the push: config lookup walks UP, and a sibling
                # command relies on finding the key at the stage level.
                lines0 = b.splitlines()
                if lines0[0].partition(" #")[0].rstrip().endswith("}"):
                    body_keys = set(re.findall(r"([A-Za-z_][A-Za-z0-9_]*)\s*:", lines0[0]))
                else:
                    body_keys = set(m.group(1) for ln in lines0
                                    for m in [re.match(r"^    ([A-Za-z_][A-Za-z0-9_]*)\s*:", ln)]
                                    if m)
                push = {k: v for k, v in inherit_vals.items() if k not in body_keys}
                pushed = ", ".join(f"{k}: {v}" for k, v in push.items())
                lines = b.splitlines()
                # flow-style detection must survive a trailing "# comment" after the "}"
                head, sep, tail = lines[0].partition(" #")
                if head.rstrip().endswith("}"):
                    l0 = head.rstrip()
                    lines[0] = (l0[:-1].rstrip().rstrip(",")
                                + (", " + pushed if pushed else "") + " }" + (sep + tail if sep else ""))
                    b = "\n".join(lines)
                elif False:
                    pass
                else:
                    # dict style: insert as the FIRST children (a block may end in column-0
                    # comments belonging to the next section -- appending would orphan the keys)
                    ins = "\n".join(f"    {k}: {v}" for k, v in push.items())
                    if ins:
                        b = lines[0] + "\n" + ins + "\n" + "\n".join(lines[1:])
            out.append(b)
        out.append("")
    # one REST server, CORS union
    out.insert(5, "rest_server:\n    cors_allow_origins: [" +
               ", ".join(f'"{u}"' for u in sorted(cors)) + "]")
    open(HERE + "live_3band.yaml", "w").write("\n".join(out) + "\n")
    print(f"wrote {HERE}live_3band.yaml")
    # sanity: parse + collision check
    import yaml
    cfg = yaml.safe_load(open(HERE + "live_3band.yaml"))
    keys = list(cfg.keys())
    assert len(keys) == len(set(keys)), "duplicate top-level keys!"
    print(f"yaml OK, {len(keys)} top-level keys, no collisions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
