#!/usr/bin/env python3
"""Generate the single-kotekan 'comb' config: F-engine -> fan out ALL 50 channels
into 50 independent single-sub-band buffers -> 50 per-channel trackers -> 50-input
combiner. This is the CHORD shape: every 195 kHz sub-band is its own stream (where
bufferSend/Recv would split across X-engine nodes), most of which carry no active
carrier and just release their frames; the ~covering channels despread their slice
and the combiner sums (sum G)/(sum E) -> full-band amplitude.

Trackers are config-seeded (PRN 10/23); the per-channel SEARCH (which needs a
central cross-channel aggregator to be useful) is a separate step. Output: one
kotekan config 'config/comb_single.yaml'.
"""

NCH = 50          # F-engine channels (200 kHz each @ 20 MSPS)
PRNS = "[10, 23]"
SEEDS_DOP = "[-1250.0, -2750.0]"
SEEDS_CP = "[647.0, 747.51]"

L = []
L.append("""---
# AUTO-GENERATED by gen_comb_config.py -- single-kotekan comb pipeline.
type: config
log_level: warn
instrument_name: airspy_gps
telescope: { name: ICETelescope, num_polarizations: 1, num_dishes: 1 }

samples_per_data_set: 50000
bytes_per_sample: 2
buffer_depth: 16
sizeof_float: 4
cpu_affinity: [0, 1, 2, 3]

spectrum_length: 50
num_taps: 4
sample_rate: 20.0e6
f_offset: 5.0e6
n_prn: 2
record_floats: 11
hops_per_record: 200
doppler_margin_hz: 900000.0
prns: """ + PRNS + """
doppler_hz: """ + SEEDS_DOP + """
code_phase_chips: """ + SEEDS_CP + """

gnss_pool: { kotekan_metadata_pool: GnssChanMetadata, num_metadata_objects: 4 * buffer_depth }

input_buf: { kotekan_buffer: standard, metadata_pool: none,      num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
chan_buf:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float }
""")

# Per-channel buffers: 500 hops * 1 ch * 8 B = 4000; records: n_prn*11*4.
for c in range(NCH):
    L.append("ch_%02d:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: 4000 }" % c)
    L.append("rec_%02d: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }" % c)
L.append("out_buf: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }")
L.append("")

L.append("""read_in: { kotekan_stage: rawFileRead, buf: input_buf, base_dir: "/tmp/gpsin_ref", file_name: "gpsin", file_ext: "raw", end_interrupt: true }
fengine: { kotekan_stage: fftwEngine, in_buf: input_buf, out_buf: chan_buf, input_type: real, pfb_window: hamming }""")

# Fan out all 50 channels, one per output buffer (comb: each sub-band its own stream).
out_bufs = "[" + ", ".join("ch_%02d" % c for c in range(NCH)) + "]"
lo = "[" + ", ".join(str(c) for c in range(NCH)) + "]"
hi = "[" + ", ".join(str(c + 1) for c in range(NCH)) + "]"
L.append("split: { kotekan_stage: GnssSubbandSplit, in_buf: chan_buf, out_bufs: %s, subband_lo: %s, subband_hi: %s }" % (out_bufs, lo, hi))
L.append("")

# One tracker per channel (channel_offset = c, n_channels = 1). Non-covering
# channels find no owned covering bin and just release their frames.
for c in range(NCH):
    L.append("track_%02d: { kotekan_stage: GnssChannelizedTracker, in_buf: ch_%02d, out_buf: rec_%02d, channel_offset: %d, n_channels: 1 }" % (c, c, c, c))
L.append("")

in_bufs = "[" + ", ".join("rec_%02d" % c for c in range(NCH)) + "]"
L.append("combiner: { kotekan_stage: GnssCoherentCombiner, in_bufs: %s, out_buf: out_buf }" % in_bufs)
L.append('write_records: { kotekan_stage: rawFileWrite, in_buf: out_buf, base_dir: "/tmp/gpscomb", file_name: "gps", file_ext: "raw", prefix_hostname: false, num_frames_per_file: 100000, exit_after_n_files: 100000 }')

open("config/comb_single.yaml", "w").write("\n".join(L) + "\n")
print("wrote config/comb_single.yaml: %d channel buffers, %d trackers, 1 combiner (%d inputs)" % (NCH, NCH, NCH))
