#!/usr/bin/env python3
"""Low-rate (2.5 MHz device = 5 MSPS RAW) version of the full live pipeline, to
test whether the 20 MSPS no-lock is USB sample drops. At 5 MSPS the airspy is
10 MB/s (vs 40 MB/s at 20 MSPS, right at the USB2 edge), so dropped samples --
which make fpga_seq skip and the code phase jump ~507 chips/frame -- should
vanish. If the cp stabilizes and locks here, drops were the cause.

Same architecture as live_full (split -> transmit -> gather -> search, + trackers
-> combiner -> recorded |A|, broker --almanac), just 5 MSPS geometry: carrier at
Fs/4 = 1.25 MHz, N=20 (125 kHz channels), covering bins ~2..18. Diagnostic
spectrum dropped to keep CPU light. Output: config/live_lowrate.yaml.
"""
N = 20
COV = list(range(2, 19))      # carrier at bin 10; main lobe +-chip_rate ~ bins 2..18
NCOV = len(COV)
PRNS = "[%s]" % ", ".join(str(p) for p in range(1, 33))
NPRN = 32
PORT0 = 15101

L = []
L.append("""---
# AUTO-GENERATED by gen_live_lowrate.py -- 5 MSPS live pipeline (drop test).
type: config
log_level: info
instrument_name: airspy_gps
telescope: { name: ICETelescope, num_polarizations: 1, num_dishes: 1 }

samples_per_data_set: 49920
bytes_per_sample: 2
buffer_depth: 16
sizeof_float: 4
cpu_affinity: [0, 1, 2, 3, 4, 5, 6, 7]

spectrum_length: %d
num_taps: 4
sample_rate: 5.0e6
f_offset: 1.25e6
signal: GPS_L1CA
code_doppler_sign: 1.0
n_prn: %d
record_floats: 11
doppler_margin_hz: 250000.0
acquire_snr: 10.0
acquire_windows: 20
doppler_min: -6000.0
doppler_max: 6000.0
doppler_step: 500.0
prns: %s

gnss_pool: { kotekan_metadata_pool: GnssChanMetadata, num_metadata_objects: 32 * buffer_depth }

input_buf: { kotekan_buffer: standard, metadata_pool: none,      num_frames: buffer_depth, frame_size: samples_per_data_set * bytes_per_sample }
chan_buf:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float }
""" % (N, NPRN, PRNS))

for c in range(N):
    L.append("ch_%02d: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, N))
for c in COV:
    L.append("rc_%02d:  { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d }" % (c, N))
    L.append("rec_%02d: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }" % c)
L.append("gather_buf: { kotekan_buffer: standard, metadata_pool: gnss_pool, num_frames: buffer_depth, frame_size: samples_per_data_set * sizeof_float / %d * %d }" % (N, NCOV))
L.append("out_buf: { kotekan_buffer: standard, metadata_pool: none, num_frames: buffer_depth, frame_size: n_prn * record_floats * sizeof_float }")
L.append("")

# Airspy at 2.5 MHz device mode -> 5 MSPS RAW (carrier @ Fs/4 = 1.25 MHz), bias on.
L.append("""airspy_in:
    kotekan_stage: airspyInput
    out_buf: input_buf
    freq: 1575.42
    sample_bw: 2.5
    gain_lna: 14
    gain_mix: 15
    gain_if: 15
    biast_power: true
fengine: { kotekan_stage: fftwEngine, in_buf: input_buf, out_buf: chan_buf, input_type: real, pfb_window: hamming }""")

out_bufs = "[" + ", ".join("ch_%02d" % c for c in range(N)) + "]"
lo = "[" + ", ".join(str(c) for c in range(N)) + "]"
hi = "[" + ", ".join(str(c + 1) for c in range(N)) + "]"
L.append("split: { kotekan_stage: GnssSubbandSplit, in_buf: chan_buf, out_bufs: %s, subband_lo: %s, subband_hi: %s }" % (out_bufs, lo, hi))
L.append("")

for i, c in enumerate(COV):
    L.append("send_%02d: { kotekan_stage: bufferSend, buf: ch_%02d, server_ip: 127.0.0.1, server_port: %d, drop_frames: false }" % (c, c, PORT0 + i))
    L.append("recv_%02d: { kotekan_stage: bufferRecv, buf: rc_%02d, listen_port: %d, num_threads: 1 }" % (c, c, PORT0 + i))
gather_in = "[" + ", ".join("rc_%02d" % c for c in COV) + "]"
L.append("gather: { kotekan_stage: GnssChannelGather, in_bufs: %s, out_buf: gather_buf }" % gather_in)
L.append("search: { kotekan_stage: GnssChannelizedSearch, in_buf: gather_buf, channel_offset: %d, n_channels: %d, acquire_snr: 10.0, acquire_windows: 20 }" % (COV[0], NCOV))
L.append("")

for c in COV:
    L.append("track_%02d: { kotekan_stage: GnssChannelizedTracker, in_buf: ch_%02d, out_buf: rec_%02d, channel_offset: %d, n_channels: 1 }" % (c, c, c, c))
comb_in = "[" + ", ".join("rec_%02d" % c for c in COV) + "]"
L.append("combiner: { kotekan_stage: GnssCoherentCombiner, in_bufs: %s, out_buf: out_buf, integration_length: 10 }" % comb_in)
L.append('record: { kotekan_stage: rawFileWrite, in_buf: out_buf, base_dir: "/tmp/gpslive", file_name: "level", file_ext: "raw", prefix_hostname: false, num_frames_per_file: 1000000, exit_after_n_files: 1000000 }')

open("config/live_lowrate.yaml", "w").write("\n".join(L) + "\n")
print("wrote config/live_lowrate.yaml: 5 MSPS, N=%d, covering %d..%d (%d ch)" % (N, COV[0], COV[-1], NCOV))
print("run: LAT=43.968697 LON=-79.252106 ALT=260 CFG=config/live_lowrate.yaml ./config/run_live.sh   (after adding CFG support)")
