##########################################
#
# raw_file_read.yaml
#
# Configuration for tracking extra beam 
# receivers' raw data file reading. It 
# does not merged the frames, only writes
# out single frame file.
#
# Author: Jing Luo
#
##########################################
---
type: config
log_level: info
cpu_affinity: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
samples_per_data_set: 49152
num_pol: 2
buffer_depth: 105

telescope:
  name: CHIMETelescope
  require_gps: true
  query_gps: true
  require_frequency_map: true
  query_frequency_map: true
  allow_default_frequency_map: false

dataset_manager:
  use_dataset_broker: false

beam_metadata_pool:
  kotekan_metadata_pool: BeamMetadata
  num_metadata_objects: 4096

beam_recv_buffer:
  kotekan_buffer: standard
  num_frames: 2048
  metadata_pool: beam_metadata_pool
  frame_size: samples_per_data_set * num_pol

raw_file_read:
  base_dir: /drives/scratch/test_beam_raw
  file_name: bass_beam_data
  read0:
    kotekan_stage: rawFileRead
    file_ext: raw
    buf: beam_recv_buffer

beam_inspect:
  kotekan_stage: BeamInspect
  in_buf: beam_recv_buffer

