##########################################
#
# transceiver_test.yaml
#
# Simple capture of packets with DPDK to test transceiver/cable losses
# Use with python/scripts/network_stat.py localhost 1 to see loss measurements
#
# Author: Andre Renard
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: INFO

samples_per_data_set: 65536
sample_block_size: 2048
buffer_depth: 10
cpu_affinity: [0,1,2,10,11,12]
num_disks: 10

# Pool
main_pool:
    kotekan_metadata_pool: chordMetadata
    num_metadata_objects: 15 * buffer_depth

# Buffers
network_buffer_0:
    kotekan_buffer: standard
    num_frames: buffer_depth * num_disks
    frame_size: samples_per_data_set * sample_block_size
    metadata_pool: main_pool
    use_hugepages: true

lost_samples_buffer_0:
    kotekan_buffer: standard
    num_frames: buffer_depth * num_disks
    frame_size: samples_per_data_set
    metadata_pool: main_pool

network_buffer_1:
    kotekan_buffer: standard
    num_frames: buffer_depth * num_disks
    frame_size: samples_per_data_set * sample_block_size
    metadata_pool: main_pool
    use_hugepages: true

lost_samples_buffer_1:
    kotekan_buffer: standard
    num_frames: buffer_depth * num_disks
    frame_size: samples_per_data_set
    metadata_pool: main_pool

network_buffer_2:
    kotekan_buffer: standard
    num_frames: buffer_depth * num_disks
    frame_size: samples_per_data_set * sample_block_size
    metadata_pool: main_pool
    use_hugepages: true

lost_samples_buffer_2:
    kotekan_buffer: standard
    num_frames: buffer_depth * num_disks
    frame_size: samples_per_data_set
    metadata_pool: main_pool

network_buffer_3:
    kotekan_buffer: standard
    num_frames: buffer_depth * num_disks
    frame_size: samples_per_data_set * sample_block_size
    metadata_pool: main_pool
    use_hugepages: true

lost_samples_buffer_3:
    kotekan_buffer: standard
    num_frames: buffer_depth * num_disks
    frame_size: samples_per_data_set
    metadata_pool: main_pool

# Stages

# The core mapping here is setup for a 6 core CPU with 12 threads (vcores)
# and setup to use the first 4 real cores (8 vcores)
dpdk:
    kotekan_stage: dpdkCore
    # Format is index = lcore, value = cpu core
    lcore_cpu_map: [4,5,6,7]
    main_lcore_cpu: 3
    fpga_packet_size: 4928
    samples_per_packet: 2
    using_switch: true
    alignment: samples_per_data_set * 100
    # Format is index = lcore, value = array of port IDs
    # so [[0,1],[2,3]] maps lcore 0 to service ports 0 and 1,
    # and lcore 1 to service ports 2 and 3.
    pcie_block_list:
        - 0d:00.0
        - 0d:00.1
        - 9f:00.0
        - 9f:00.1
    lcore_port_map:
        - [0]
        - [1]
        - [2]
        - [3]
    # One handler must be given per port on the system.
    handlers:
        - dpdk_handler: iceBoardStandard
          out_buf: network_buffer_0
          lost_samples_buf: lost_samples_buffer_0
        - dpdk_handler: iceBoardStandard
          out_buf: network_buffer_1
          lost_samples_buf: lost_samples_buffer_1
        - dpdk_handler: iceBoardStandard
          out_buf: network_buffer_2
          lost_samples_buf: lost_samples_buffer_2
        - dpdk_handler: iceBoardStandard
          out_buf: network_buffer_3
          lost_samples_buf: lost_samples_buffer_3
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none
        - dpdk_handler: none

zero_samples_0:
    kotekan_stage: zeroSamples
    out_buf: network_buffer_0
    lost_samples_buf: lost_samples_buffer_0
    zero_value: 0x88

zero_samples_0:
    kotekan_stage: zeroSamples
    out_buf: network_buffer_1
    lost_samples_buf: lost_samples_buffer_1
    zero_value: 0x88

zero_samples_0:
    kotekan_stage: zeroSamples
    out_buf: network_buffer_2
    lost_samples_buf: lost_samples_buffer_2
    zero_value: 0x88

zero_samples_0:
    kotekan_stage: zeroSamples
    out_buf: network_buffer_3
    lost_samples_buf: lost_samples_buffer_3
    zero_value: 0x88


