# verify_outrigger_beamformer.yaml
# Config to test the opencl stack

---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
#https://github.com/kotekan/kotekan/blob/abp/outrigger_beamformer/config/chime_hco_gpu.j2
log_level: debug2

num_data_sets: 1
num_pointings: 1
num_links: 16     
samples_per_data_set: 32  
buffer_depth: 8 #12 #num_gpu_frames: 4
cpu_affinity: [2,3,4,5,8,9,10,11]
num_elements: 32 #256 #2048
num_local_freq: 1
sizeof_int: 4
sizeof_float: 4

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 15 * buffer_depth

# Buffers
gpu_input_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_elements * num_local_freq * num_data_sets * sizeof_int
    metadata_pool: main_pool
    gpu_input_buffer:
        kotekan_buffer: standard

gpu_phase_buffer: 
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size:  num_elements * num_local_freq * num_data_sets * num_pointings * sizeof_int
    metadata_pool: main_pool


gpu_output_buffers:
    frame_size: samples_per_data_set * num_data_sets * num_local_freq * num_pointings * 2 * sizeof_int #samples_per_data_set * num_data_sets * num_local_freq * 2
    metadata_pool: main_pool
    num_frames: buffer_depth
    gpu_output_buffer:
        kotekan_buffer: standard

gen_data:
  type: const32 #const
  value: 2
  kotekan_stage: testDataGen
  out_buf: gpu_input_buffer

gen_phases:
  type: constf32 #const
  value: 1.0
  kotekan_stage: testDataGen
  out_buf: gpu_phase_buffer

#data_format: dot4b
# data_format: "4+4b"
#full_complicated: false #don't use the ISA-like kernel: intrinsics, extra packing, overflows, etc

gpu:
  profiling: true
  kernel_path: "/home/shiona/kotekan/lib/opencl/kernels"
  gain_dir: "/etc/kotekan/"
  log_level: debug2 #buffer_depth: 8
  frame_arrival_period: 390625
  commands: &command_list
  - name: clInputData
    gpu_memory: input
    in_bufs:
      - network_buf
  - name: clInputData
    gpu_memory: phases
    in_bufs:
      - phases_buf
  - name: clOutputDataZero
  - name: clBeamformKernel
  - name: clOutputData
    out_bufs:
       - output_buf
    in_bufs:
       - network_buf
  gpu_0:
    kotekan_stage: clProcess
    gpu_id: 0
    commands: *command_list
    in_buffers:
      network_buf: gpu_input_buffer
      phases_buf: gpu_phase_buffer
    out_buffers:
      output_buf: gpu_output_buffer

cpu:
   kotekan_stage: bkCheck
   log_level: debug2
   network_in_buf: gpu_output_buffer

