set (KOTEKAN_UTIL_SOURCES
        fpga_header_functions.c
        gateSpec.cpp
        gpsTime.c
        nt_memcpy.c
        nt_memset.c
        output_formating.c
        time_tracking.c
        util.c
        visBuffer.cpp
        visUtil.cpp
        visFile.cpp
        visFileRaw.cpp
        visFileRing.cpp
        tx_utils.cpp
        datasetManager.cpp
        pulsarTiming.cpp
        datasetState.cpp
        restClient.cpp
    )
