##########################################
#
# verify_cuda_n2k_pl1bitcorr.yaml
#
# Config to test Kendrick's cuda N2 tensor-core Packet Loss Correlator kernel.
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: INFO

num_gpus: 1
buffer_depth: 4
cpu_affinity: [2,3,4,5,8,9,10,11]
sizeof_float: 4
frame_arrival_period: 5.12e-6 * samples_per_data_set
sizeof_int: 4

# For faster CHORD testing, we're using...
sub_integration_ntime: 2048
samples_per_data_set: 4096
# sub_integration_ntime: 8192  # ~40 ms for chord
# samples_per_data_set: 8192   # 
num_times: samples_per_data_set
num_polarizations: 2
num_dishes: 64
num_elements: num_polarizations * num_dishes
num_local_freq: 16

#counts matrix size
counts_blocksize: 8
counts_num_blocks_lin: (num_elements / 8) / counts_blocksize
counts_num_blocks: (counts_num_blocks_lin * (counts_num_blocks_lin + 1)) / 2

# Pool
main_pool:
    kotekan_metadata_pool: chordMetadata
    num_metadata_objects: 16 * buffer_depth

# Buffers
host_pl_mask_exp_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set * num_local_freq * (num_elements / 8)) / 8
    metadata_pool: main_pool

host_rfi_RFImask_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: num_local_freq * samples_per_data_set / 8
    metadata_pool: main_pool

host_counts_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / sub_integration_ntime) * num_local_freq * counts_num_blocks * counts_blocksize * counts_blocksize * sizeof_int
    metadata_pool: main_pool

simulated_counts_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: (samples_per_data_set / sub_integration_ntime) * num_local_freq * counts_num_blocks * counts_blocksize * counts_blocksize * sizeof_int
    metadata_pool: main_pool

# Ringbuffer signalling buffer
host_pl_mask_exp_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * (samples_per_data_set * num_local_freq * (num_elements / 8)) / 8
    metadata_pool: main_pool

host_rfi_RFImask_ringbuffer:
    kotekan_buffer: ring
    ring_buffer_size: buffer_depth * samples_per_data_set * num_local_freq / 8
    metadata_pool: main_pool

gen_pl_exp_mask:
    type: random1x8
    value: 120
    kotekan_stage: testDataGen
    out_buf: host_pl_mask_exp_buffer
    name: "pl_mask"
    array_shape: [ 64, 16, 2, 8, 8 ]  # = num_times/64, num_freq, 2, num_dishes/8, 8
    dim_name: ["Thi64", "F", "P", "D8", "Tlo64" ]
    num_frames: buffer_depth  # Must be at least what check_data expects
    meta_time_downsample_factor: 64  # The number of time samples represented by each coarse time index.

gen_data_rfi_RFImask:
    type: random1x8
    value: 255
    kotekan_stage: testDataGen
    out_buf: host_rfi_RFImask_buffer
    name: "RFImask"
    array_shape: [ 4, 16, 128 ]
    dim_name: ["T8hi128", "F", "T8lo128"]
    num_frames: buffer_depth
    meta_time_downsample_factor: 1024  # The number of time samples represented by each coarse time index.

run_send_pl_mask:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_pl_mask_exp_buffer_in: host_pl_mask_exp_buffer
        out_buffers:
            host_pl_mask_exp_ringbuffer_out: host_pl_mask_exp_ringbuffer
        commands:
        - name: cudaCopyToRingbuffer
          input_size: samples_per_data_set * num_local_freq * (num_elements/8) / 8
          ring_buffer_size: buffer_depth * input_size
          in_buf: host_pl_mask_exp_buffer_in
          signal_buf: host_pl_mask_exp_ringbuffer_out
          gpu_mem_output: pl_mask_exp_buffer

run_send_rfi_RFImask:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_rfi_RFImask_buffer_in: host_rfi_RFImask_buffer
        out_buffers:
            host_rfi_RFImask_ringbuffer_out: host_rfi_RFImask_ringbuffer
        commands:
        - name: cudaCopyToRingbuffer
          input_size: samples_per_data_set * num_local_freq / 8
          ring_buffer_size: buffer_depth * input_size
          in_buf: host_rfi_RFImask_buffer_in
          signal_buf: host_rfi_RFImask_ringbuffer_out
          gpu_mem_output: rfi_RFImask_buffer

run_pl_corr:
    gpu_0:
        kotekan_stage: cudaProcess
        gpu_id: 0
        in_buffers:
            host_pl_mask_exp_ringbuffer: host_pl_mask_exp_ringbuffer
            host_rfi_RFImask_ringbuffer: host_rfi_RFImask_ringbuffer
        out_buffers:
            host_counts_buffer: host_counts_buffer
        commands:
        - name: cudaPL1bitCorrelator
          num_frequencies: num_local_freq
          pl_expanded_mask_name: pl_mask_exp
          rfi_RFImask_name: rfi_RFImask
          n2k_counts_name: counts
        - name: cudaSyncOutput
        - name: cudaOutputData
          gpu_mem: counts_buffer
          out_buf: host_counts_buffer

cpu:
    kotekan_stage: gpuSimulateN2kPL1bitCorr
    log_level: debug
    in_plmask_buf: host_pl_mask_exp_buffer
    in_rfimask_buf: host_rfi_RFImask_buffer
    out_buf: simulated_counts_buffer

check_data:
    kotekan_stage: testDataCheckInt
    first_buf: host_counts_buffer
    second_buf: simulated_counts_buffer
    num_frames_to_test: buffer_depth
    check_metadata: True
