#!/bin/bash
#
#       /etc/rc.d/init.d/kotekan
#
#       The CHIME GPU X Correlator
#

# Source function library.
. /etc/init.d/functions

# The kotekan binary.
ROOTDIR=/root/kotekan/
KOTEKAN=${ROOTDIR}/bin/kotekan

PIDFILE=/var/run/kotekan.pid
LOCKFILE=/var/lock/subsys/kotekan

# This config setup is not ideal, but will be removed once ch_master sets the config.
CONFIG=${ROOTDIR}/conf/kotekan_`hostname`.conf
OPTIONS="-l 3 -c ${CONFIG}"

start() {
        echo -n $"Starting korekan: "
        ${KOTEKAN} -d ${ROOTDIR} ${OPTIONS} && success || failure
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch ${LOCKFILE}
        echo
        return $RETVAL
}

stop() {
        echo -n "Stopping kotekan: "
        killproc -p ${PIDFILE} ${KOTEKAN}
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f ${LOCKFILE}
        echo
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p ${PIDFILE} kotekan
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: kotekan {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
