name: readthedocs

channels:
  - conda-forge
  - default

dependencies:
  - python=3.11
  - pip
  - cmake
  - doxygen
  - sphinx=5.0.2
  - sphinx_rtd_theme=1.2.2
  - breathe=4.35.0
  - sphinxcontrib-plantuml=0.25
