# All user-facing build options (no logic here)

option(USE_AIRSPY "Build Airspy Producer" OFF)
option(USE_FFTW "Build with FFTW F-engine" ON)
option(USE_LAPACK_BLAZE "Build with LAPACK Linear Algebra (OpenBLAS) and Blaze support" ON)
option(USE_OPENCL "Build OpenCL GPU Framework" OFF)
option(USE_CUDA "Build CUDA GPU Framework" OFF)
option(USE_HIP "Build HIP GPU Framework" OFF)
option(USE_OLD_DPDK "Enable old versions of DPDK (<19.11)" OFF)
option(USE_ASDF "Build ASDF output stages" ON)
option(USE_GDAL "Build GDAL output stages" ON)
option(USE_HDF5 "Build HDF5 output stages" ON)
option(USE_JULIA "Build Julia-based features" ON)
option(USE_OMP "Enable OpenMP" OFF)
option(USE_OLD_ROCM "Build for ROCm versions 2.3 or older" OFF)
option(NO_MEMLOCK "Do not lock buffer memory (useful when running in Docker)" OFF)
option(SUPERDEBUG "Enable extra debugging with no optimisation" OFF)
option(SANITIZE "Enable clang sanitizers for testing" OFF)
option(COMPILE_DOCS "Use Sphinx to compile documentation" OFF)
option(WITH_TESTS "Build and link lib/testing helper library (does not build Boost unit tests)" OFF)
option(WITH_BOOST_TESTS "Compile boost C++ unit tests" OFF)
option(IWYU "Enable include-what-you-use and print suggestions to stderr" OFF)
option(CCACHE "Use ccache to speed up the build" OFF)
option(WERROR "Warnings are errors" OFF)
