# Final feature summary table

include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/Color.cmake)

# Column widths for aligned summary output
set(_kfeature_name_col_width 24)
set(_kfeature_state_col_width 3)

# kpad_right: pad a string on the right with spaces up to a fixed width
function(kpad_right out_var in_str width)
    string(LENGTH "${in_str}" len)
    set(res "${in_str}")
    math(EXPR pad "${width} - ${len}")
    if(pad GREATER 0)
        set(spaces "")
        while(pad GREATER 0)
            set(spaces "${spaces} ")
            math(EXPR pad "${pad} - 1")
        endwhile()
        set(res "${res}${spaces}")
    endif()
    set(${out_var}
        "${res}"
        PARENT_SCOPE)
endfunction()

# kfeature_row: print one aligned feature row; optional 5th arg is toggle var (e.g., USE_CUDA)
function(kfeature_row name enabled reason present)
    set(toggle_var "")
    if(ARGC GREATER 4)
        set(toggle_var "${ARGV4}")
    endif()
    # Determine color and state token
    set(state "OFF")
    set(color "${KTK_YELLOW}")
    if(enabled)
        set(state "ON")
        set(color "${KTK_GREEN}")
    else()
        string(TOLOWER "${reason}" reason_lc)
        if(present)
            set(color "${KTK_YELLOW}")
        elseif(reason_lc MATCHES "missing|not found|not runnable")
            set(color "${KTK_RED}")
        else()
            set(color "${KTK_YELLOW}")
        endif()
    endif()

    # Pad columns so that the parenthetical notes align
    set(name_col "${name}:")
    kpad_right(name_col "${name_col}" ${_kfeature_name_col_width})
    kpad_right(state_col "${state}" ${_kfeature_state_col_width})

    set(toggle_note "")
    if(NOT "${toggle_var}" STREQUAL "")
        # If the toggle is a cached BOOL option, show the explicit command-line form with =ON/=OFF.
        # Otherwise, just show -D<VAR>.
        get_property(
            _ktk_toggle_type
            CACHE ${toggle_var}
            PROPERTY TYPE)
        if("${_ktk_toggle_type}" STREQUAL "BOOL")
            if(enabled)
                set(toggle_note ", -D${toggle_var}=ON")
            else()
                set(toggle_note ", -D${toggle_var}=OFF")
            endif()
        else()
            set(toggle_note ", -D${toggle_var}")
        endif()
    endif()
    message(STATUS "${color}${name_col} ${state_col} (${reason}${toggle_note})${KTK_RESET}")
endfunction()

# kfeature_header: print a section header in the summary
function(kfeature_header title)
    kmsg_status("")
    kmsg_status("==== ${title} ====")
endfunction()

# Key/Value printer for build metadata kfeature_kv: print a key/value line in the summary
function(kfeature_kv name value)
    kmsg_status("${name}: ${value}")
endfunction()

# GPU
kfeature_header("GPU Features")
# Alphabetical: CUDA, HIP, OpenCL
kfeature_row("CUDA" "${CUDA_ENABLED}" "${CUDA_REASON}" OFF USE_CUDA)
kfeature_row("HIP" "${HIP_ENABLED}" "${HIP_REASON}" OFF USE_HIP)
kfeature_row("OpenCL" "${OPENCL_ENABLED}" "${OPENCL_REASON}" OFF USE_OPENCL)

# IO
kfeature_header("I/O Formats")
set(_asdf_present OFF)
if(NOT ASDF_ENABLED)
    find_package(asdf-cxx QUIET)
    set(_asdf_present ${ASDF_CXX_FOUND})
endif()
kfeature_row("ASDF" "${ASDF_ENABLED}" "${ASDF_REASON}" "${_asdf_present}" USE_ASDF)

set(_gdal_present OFF)
if(NOT GDAL_ENABLED)
    find_package(GDAL QUIET)
    set(_gdal_present ${GDAL_FOUND})
endif()
kfeature_row("GDAL" "${GDAL_ENABLED}" "${GDAL_REASON}" "${_gdal_present}" USE_GDAL)

set(_hdf5_present OFF)
if(NOT HDF5_ENABLED)
    find_package(HDF5 QUIET)
    find_package(HighFive QUIET)
    if(HDF5_FOUND AND HighFive_FOUND)
        set(_hdf5_present ON)
    endif()
endif()
kfeature_row("HDF5" "${HDF5_ENABLED}" "${HDF5_REASON}" "${_hdf5_present}" USE_HDF5)

# Math
kfeature_header("Math")
set(_fftw_present OFF)
if(NOT FFTW_ENABLED)
    find_package(FFTW QUIET)
    set(_fftw_present ${FFTW_FOUND})
endif()
kfeature_row("FFTW" "${FFTW_ENABLED}" "${FFTW_REASON}" "${_fftw_present}" USE_FFTW)

set(_lapack_blaze_present OFF)
if(NOT LAPACK_BLAZE_ENABLED)
    find_package(LAPACKE QUIET)
    find_package(Blaze QUIET)
    if(LAPACKE_FOUND AND BLAZE_FOUND)
        set(_lapack_blaze_present ON)
    endif()
endif()
kfeature_row("LAPACK/Blaze" "${LAPACK_BLAZE_ENABLED}" "${LAPACK_BLAZE_REASON}"
             "${_lapack_blaze_present}" USE_LAPACK_BLAZE)

# Other
kfeature_header("Other")
# Alphabetical: Airspy, DPDK, Julia, NUMA, OpenMP, OpenSSL
set(AIRSPY_ENABLED ${USE_AIRSPY})
if(${USE_AIRSPY})
    set(AIRSPY_REASON "enabled")
else()
    set(AIRSPY_REASON "disabled")
endif()
kfeature_row("Airspy" "${AIRSPY_ENABLED}" "${AIRSPY_REASON}" OFF USE_AIRSPY)
if(DEFINED DPDK_ENABLED)
    # Note: When WITH_BOOST_TESTS=ON, DPDK is disabled to avoid linker issues
    kfeature_row("DPDK" "${DPDK_ENABLED}" "${DPDK_REASON}" OFF)
endif()
kfeature_row("Julia" "${JULIA_ENABLED}" "${JULIA_REASON}" OFF USE_JULIA)
if(DEFINED NUMA_ENABLED)
    # Optional: can be toggled with -DUSE_NUMA=ON|OFF
    kfeature_row("NUMA" "${NUMA_ENABLED}" "${NUMA_REASON}" OFF USE_NUMA)
endif()
set(OMP_ENABLED ${USE_OMP})
if(${USE_OMP})
    set(OMP_REASON "enabled")
else()
    set(OMP_REASON "disabled")
endif()
kfeature_row("OpenMP" "${OMP_ENABLED}" "${OMP_REASON}" OFF USE_OMP)
if(DEFINED OPENSSL_ENABLED)
    # Optional: can be toggled with -DUSE_OPENSSL=ON|OFF
    if(OPENSSL_ENABLED)
        kfeature_row("OpenSSL" "${OPENSSL_ENABLED}" "${OPENSSL_REASON}" OFF USE_OPENSSL)
    else()
        # Hint: use -DOPENSSL_ROOT_DIR=<path> for non-standard installs
        set(_ossl_reason
            "${OPENSSL_REASON}; use -DOPENSSL_ROOT_DIR=<path> for non-standard installs")
        kfeature_row("OpenSSL" "${OPENSSL_ENABLED}" "${_ossl_reason}" OFF USE_OPENSSL)
    endif()
endif()

# Build meta
kfeature_header("Build")
# Build Type aligned so value starts where ON/OFF would
set(_bt_name "Build Type:")
kpad_right(_bt_name "${_bt_name}" ${_kfeature_name_col_width})
kmsg_status("${_bt_name} ${CMAKE_BUILD_TYPE} (-DCMAKE_BUILD_TYPE=Debug|Release|Test)")
set(DOCS_ENABLED ${COMPILE_DOCS})
if(${COMPILE_DOCS})
    set(DOCS_REASON "enabled")
else()
    set(DOCS_REASON "disabled")
endif()
kfeature_row("Docs" "${DOCS_ENABLED}" "${DOCS_REASON}" OFF COMPILE_DOCS)
set(TESTS_ENABLED ${WITH_TESTS})
if(${WITH_TESTS})
    set(TESTS_REASON "enabled: builds and links lib/testing")
else()
    set(TESTS_REASON "disabled")
endif()
kfeature_row("C++ Tests (lib)" "${TESTS_ENABLED}" "${TESTS_REASON}" OFF WITH_TESTS)
set(BOOSTTEST_ENABLED ${WITH_BOOST_TESTS})
if(${WITH_BOOST_TESTS})
    set(BOOSTTEST_REASON "enabled: builds tests/boost and disables DPDK")
else()
    set(BOOSTTEST_REASON "disabled")
endif()
kfeature_row("Boost Tests" "${BOOSTTEST_ENABLED}" "${BOOSTTEST_REASON}" OFF WITH_BOOST_TESTS)
set(NOMEMLOCK_ENABLED ${NO_MEMLOCK})
if(${NO_MEMLOCK})
    set(NOMEMLOCK_REASON "enabled")
else()
    set(NOMEMLOCK_REASON "disabled")
endif()
kfeature_row("No Memlock" "${NOMEMLOCK_ENABLED}" "${NOMEMLOCK_REASON}" OFF NO_MEMLOCK)
kfeature_row("ccache" "${CCACHE_ENABLED}" "${CCACHE_REASON}" OFF CCACHE)
set(WERROR_REASON "disabled")
if(${WERROR_ENABLED})
    set(WERROR_REASON "enabled")
endif()
kfeature_row("Warnings-as-errors" "${WERROR_ENABLED}" "${WERROR_REASON}" OFF WERROR)
set(IWYU_REASON "disabled")
if(${IWYU_ENABLED})
    set(IWYU_REASON "enabled")
endif()
kfeature_row("include-what-you-use" "${IWYU_ENABLED}" "${IWYU_REASON}" OFF IWYU)

# Compilers
kfeature_header("Compilers")
set(_c_vers ${CMAKE_C_COMPILER_VERSION})
if(NOT _c_vers)
    set(_c_vers "unknown")
endif()
set(_cxx_vers ${CMAKE_CXX_COMPILER_VERSION})
if(NOT _cxx_vers)
    set(_cxx_vers "unknown")
endif()
kfeature_kv("C" "${CMAKE_C_COMPILER_ID} ${_c_vers} (${CMAKE_C_COMPILER})")
kfeature_kv("C++" "${CMAKE_CXX_COMPILER_ID} ${_cxx_vers} (${CMAKE_CXX_COMPILER})")
if(CUDA_ENABLED)
    set(_cuda_vers ${CMAKE_CUDA_COMPILER_VERSION})
    if(NOT _cuda_vers)
        set(_cuda_vers "unknown")
    endif()
    kfeature_kv("CUDA" "NVCC ${_cuda_vers} (${CMAKE_CUDA_COMPILER})")
endif()

kmsg_status("")
