# Final feature summary table

include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/Color.cmake)

# Column widths for aligned summary output
set(_KFEATURE_NAME_COL_WIDTH 24)
set(_KFEATURE_STATE_COL_WIDTH 3)

# Right-pad a string with spaces to a fixed width (CMake 3.8-compatible)
function(kpad_right OUT_VAR IN_STR WIDTH)
    string(LENGTH "${IN_STR}" _len)
    set(_res "${IN_STR}")
    math(EXPR _pad "${WIDTH} - ${_len}")
    if(_pad GREATER 0)
        set(_spaces "")
        while(_pad GREATER 0)
            set(_spaces "${_spaces} ")
            math(EXPR _pad "${_pad} - 1")
        endwhile()
        set(_res "${_res}${_spaces}")
    endif()
    set(${OUT_VAR} "${_res}" PARENT_SCOPE)
endfunction()

function(kfeature_row NAME ENABLED REASON PRESENT)
    # Optional 5th arg: toggle variable name (e.g., USE_CUDA)
    set(_toggle_var "")
    if(ARGC GREATER 4)
        set(_toggle_var "${ARGV4}")
    endif()
    # Determine color and state token
    set(_state "OFF")
    set(_color "${KTK_YELLOW}")
    if(ENABLED)
        set(_state "ON")
        set(_color "${KTK_GREEN}")
    else()
        string(TOLOWER "${REASON}" _reason_lc)
        if(PRESENT)
            set(_color "${KTK_YELLOW}")
        elseif(_reason_lc MATCHES "missing|not found|not runnable")
            set(_color "${KTK_RED}")
        else()
            set(_color "${KTK_YELLOW}")
        endif()
    endif()

    # Pad columns so that the parenthetical notes align
    set(_name_col "${NAME}:")
    kpad_right(_name_col "${_name_col}" ${_KFEATURE_NAME_COL_WIDTH})
    kpad_right(_state_col "${_state}" ${_KFEATURE_STATE_COL_WIDTH})

    set(_toggle_note "")
    if(NOT "${_toggle_var}" STREQUAL "")
        set(_toggle_note ", -D${_toggle_var}=ON/OFF")
    endif()
    message(STATUS "${_color}${_name_col} ${_state_col} (${REASON}${_toggle_note})${KTK_RESET}")
endfunction()

function(kfeature_header TITLE)
    kmsg_status("")
    kmsg_status("==== ${TITLE} ====")
endfunction()

# Key/Value printer for build metadata
function(kfeature_kv NAME VALUE)
    kmsg_status("${NAME}: ${VALUE}")
endfunction()

# GPU
kfeature_header("GPU Features")
kfeature_row("CUDA" "${CUDA_ENABLED}" "${CUDA_REASON}" OFF USE_CUDA)
kfeature_row("OpenCL" "${OPENCL_ENABLED}" "${OPENCL_REASON}" OFF USE_OPENCL)
kfeature_row("HIP" "${HIP_ENABLED}" "${HIP_REASON}" OFF USE_HIP)

# IO
kfeature_header("I/O Formats")
set(_ASDF_PRESENT OFF)
if(NOT ASDF_ENABLED)
    find_package(asdf-cxx QUIET)
    set(_ASDF_PRESENT ${ASDF_CXX_FOUND})
endif()
kfeature_row("ASDF" "${ASDF_ENABLED}" "${ASDF_REASON}" "${_ASDF_PRESENT}" USE_ASDF)

set(_GDAL_PRESENT OFF)
if(NOT GDAL_ENABLED)
    find_package(GDAL QUIET)
    set(_GDAL_PRESENT ${GDAL_FOUND})
endif()
kfeature_row("GDAL" "${GDAL_ENABLED}" "${GDAL_REASON}" "${_GDAL_PRESENT}" USE_GDAL)

set(_HDF5_PRESENT OFF)
if(NOT HDF5_ENABLED)
    find_package(HDF5 QUIET)
    find_package(HighFive QUIET)
    if(HDF5_FOUND AND HighFive_FOUND)
        set(_HDF5_PRESENT ON)
    endif()
endif()
kfeature_row("HDF5" "${HDF5_ENABLED}" "${HDF5_REASON}" "${_HDF5_PRESENT}" USE_HDF5)

# Math
kfeature_header("Math")
set(_FFTW_PRESENT OFF)
if(NOT FFTW_ENABLED)
    find_package(FFTW QUIET)
    set(_FFTW_PRESENT ${FFTW_FOUND})
endif()
kfeature_row("FFTW" "${FFTW_ENABLED}" "${FFTW_REASON}" "${_FFTW_PRESENT}" USE_FFTW)

set(_LAPACK_BLAZE_PRESENT OFF)
if(NOT LAPACK_BLAZE_ENABLED)
    find_package(LAPACKE QUIET)
    find_package(Blaze QUIET)
    if(LAPACKE_FOUND AND BLAZE_FOUND)
        set(_LAPACK_BLAZE_PRESENT ON)
    endif()
endif()
kfeature_row("LAPACK/Blaze" "${LAPACK_BLAZE_ENABLED}" "${LAPACK_BLAZE_REASON}"
             "${_LAPACK_BLAZE_PRESENT}" USE_LAPACK_BLAZE)

# Other
kfeature_header("Other")
set(AIRSPY_ENABLED ${USE_AIRSPY})
if(${USE_AIRSPY})
    set(AIRSPY_REASON "enabled")
else()
    set(AIRSPY_REASON "disabled")
endif()
kfeature_row("Airspy" "${AIRSPY_ENABLED}" "${AIRSPY_REASON}" OFF USE_AIRSPY)
set(OMP_ENABLED ${USE_OMP})
if(${USE_OMP})
    set(OMP_REASON "enabled")
else()
    set(OMP_REASON "disabled")
endif()
kfeature_row("OpenMP" "${OMP_ENABLED}" "${OMP_REASON}" OFF USE_OMP)
kfeature_row("Julia" "${JULIA_ENABLED}" "${JULIA_REASON}" OFF USE_JULIA)
# From lib/core: NUMA and OpenSSL
if(DEFINED NUMA_ENABLED)
    kfeature_row("NUMA" "${NUMA_ENABLED}" "${NUMA_REASON}" OFF)
endif()
if(DEFINED OPENSSL_ENABLED)
    kfeature_row("OpenSSL" "${OPENSSL_ENABLED}" "${OPENSSL_REASON}" OFF)
endif()
if(DEFINED DPDK_ENABLED)
    # Note: When WITH_BOOST_TESTS=ON, DPDK is disabled to avoid linker issues
    kfeature_row("DPDK" "${DPDK_ENABLED}" "${DPDK_REASON}, -DUSE_OLD_DPDK=ON/OFF" OFF)
endif()

# Build meta
kfeature_header("Build")
kfeature_kv("Build Type" "${CMAKE_BUILD_TYPE} (-DCMAKE_BUILD_TYPE=Debug|Release|Test)")
set(DOCS_ENABLED ${COMPILE_DOCS})
if(${COMPILE_DOCS})
    set(DOCS_REASON "enabled")
else()
    set(DOCS_REASON "disabled")
endif()
kfeature_row("Docs" "${DOCS_ENABLED}" "${DOCS_REASON}" OFF COMPILE_DOCS)
set(TESTS_ENABLED ${WITH_TESTS})
if(${WITH_TESTS})
    set(TESTS_REASON "enabled: builds and links lib/testing")
else()
    set(TESTS_REASON "disabled")
endif()
kfeature_row("C++ Tests (lib)" "${TESTS_ENABLED}" "${TESTS_REASON}" OFF WITH_TESTS)
set(BOOSTTEST_ENABLED ${WITH_BOOST_TESTS})
if(${WITH_BOOST_TESTS})
    set(BOOSTTEST_REASON "enabled: builds tests/boost and disables DPDK")
else()
    set(BOOSTTEST_REASON "disabled")
endif()
kfeature_row("Boost Tests" "${BOOSTTEST_ENABLED}" "${BOOSTTEST_REASON}" OFF WITH_BOOST_TESTS)
set(NOMEMLOCK_ENABLED ${NO_MEMLOCK})
if(${NO_MEMLOCK})
    set(NOMEMLOCK_REASON "enabled")
else()
    set(NOMEMLOCK_REASON "disabled")
endif()
kfeature_row("No Memlock" "${NOMEMLOCK_ENABLED}"
             "${NOMEMLOCK_REASON}, -DNO_MEMLOCK=ON/OFF" OFF)
kfeature_row("ccache" "${CCACHE_ENABLED}" "${CCACHE_REASON}, -DCCACHE=ON/OFF" OFF)
set(WERROR_REASON "disabled")
if(${WERROR_ENABLED})
    set(WERROR_REASON "enabled")
endif()
kfeature_row("Warnings-as-errors" "${WERROR_ENABLED}" "${WERROR_REASON}, -DWERROR=ON/OFF"
             OFF)
set(IWYU_REASON "disabled")
if(${IWYU_ENABLED})
    set(IWYU_REASON "enabled")
endif()
kfeature_row("include-what-you-use" "${IWYU_ENABLED}" "${IWYU_REASON}, -DIWYU=ON/OFF" OFF)

# Compilers
kfeature_header("Compilers")
set(_C_VERS ${CMAKE_C_COMPILER_VERSION})
if(NOT _C_VERS)
    set(_C_VERS "unknown")
endif()
set(_CXX_VERS ${CMAKE_CXX_COMPILER_VERSION})
if(NOT _CXX_VERS)
    set(_CXX_VERS "unknown")
endif()
kfeature_kv("C" "${CMAKE_C_COMPILER_ID} ${_C_VERS} (${CMAKE_C_COMPILER})")
kfeature_kv("C++" "${CMAKE_CXX_COMPILER_ID} ${_CXX_VERS} (${CMAKE_CXX_COMPILER})")
if(CUDA_ENABLED)
    set(_CUDA_VERS ${CMAKE_CUDA_COMPILER_VERSION})
    if(NOT _CUDA_VERS)
        set(_CUDA_VERS "unknown")
    endif()
    kfeature_kv("CUDA" "NVCC ${_CUDA_VERS} (${CMAKE_CUDA_COMPILER})")
endif()

kmsg_status("")
