# Final feature summary table

include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/Color.cmake)

function(kfeature_row NAME ENABLED REASON PRESENT)
    if(ENABLED)
        message(STATUS "${KTK_GREEN}${NAME}: ON  (${REASON})${KTK_RESET}")
    else()
        string(TOLOWER "${REASON}" _reason_lc)
        if(PRESENT)
            message(STATUS "${KTK_YELLOW}${NAME}: OFF  (${REASON})${KTK_RESET}")
        elseif(_reason_lc MATCHES "missing|not found|not runnable")
            message(STATUS "${KTK_RED}${NAME}: OFF  (${REASON})${KTK_RESET}")
        else()
            message(STATUS "${KTK_YELLOW}${NAME}: OFF  (${REASON})${KTK_RESET}")
        endif()
    endif()
endfunction()

function(kfeature_header TITLE)
    kmsg_status("")
    kmsg_status("==== ${TITLE} ====")
endfunction()

# Key/Value printer for build metadata
function(kfeature_kv NAME VALUE)
    kmsg_status("${NAME}: ${VALUE}")
endfunction()

# GPU
kfeature_header("GPU Features")
kfeature_row("CUDA" "${CUDA_ENABLED}" "${CUDA_REASON}" OFF)
kfeature_row("OpenCL" "${OPENCL_ENABLED}" "${OPENCL_REASON}" OFF)
kfeature_row("HIP" "${HIP_ENABLED}" "${HIP_REASON}" OFF)

# IO
kfeature_header("I/O Formats")
set(_ASDF_PRESENT OFF)
if(NOT ASDF_ENABLED)
    find_package(asdf-cxx QUIET)
    set(_ASDF_PRESENT ${ASDF_CXX_FOUND})
endif()
kfeature_row("ASDF" "${ASDF_ENABLED}" "${ASDF_REASON}" "${_ASDF_PRESENT}")

set(_GDAL_PRESENT OFF)
if(NOT GDAL_ENABLED)
    find_package(GDAL QUIET)
    set(_GDAL_PRESENT ${GDAL_FOUND})
endif()
kfeature_row("GDAL" "${GDAL_ENABLED}" "${GDAL_REASON}" "${_GDAL_PRESENT}")

set(_HDF5_PRESENT OFF)
if(NOT HDF5_ENABLED)
    find_package(HDF5 QUIET)
    find_package(HighFive QUIET)
    if(HDF5_FOUND AND HighFive_FOUND)
        set(_HDF5_PRESENT ON)
    endif()
endif()
kfeature_row("HDF5" "${HDF5_ENABLED}" "${HDF5_REASON}" "${_HDF5_PRESENT}")

# Math
kfeature_header("Math")
set(_FFTW_PRESENT OFF)
if(NOT FFTW_ENABLED)
    find_package(FFTW QUIET)
    set(_FFTW_PRESENT ${FFTW_FOUND})
endif()
kfeature_row("FFTW" "${FFTW_ENABLED}" "${FFTW_REASON}" "${_FFTW_PRESENT}")

set(_LAPACK_BLAZE_PRESENT OFF)
if(NOT LAPACK_BLAZE_ENABLED)
    find_package(LAPACKE QUIET)
    find_package(Blaze QUIET)
    if(LAPACKE_FOUND AND BLAZE_FOUND)
        set(_LAPACK_BLAZE_PRESENT ON)
    endif()
endif()
kfeature_row("LAPACK/Blaze" "${LAPACK_BLAZE_ENABLED}" "${LAPACK_BLAZE_REASON}"
             "${_LAPACK_BLAZE_PRESENT}")

# Other
kfeature_header("Other")
set(AIRSPY_ENABLED ${USE_AIRSPY})
if(${USE_AIRSPY})
    set(AIRSPY_REASON "enabled")
else()
    set(AIRSPY_REASON "disabled")
endif()
kfeature_row("Airspy" "${AIRSPY_ENABLED}" "${AIRSPY_REASON}" OFF)
set(OMP_ENABLED ${USE_OMP})
if(${USE_OMP})
    set(OMP_REASON "enabled")
else()
    set(OMP_REASON "disabled")
endif()
kfeature_row("OpenMP" "${OMP_ENABLED}" "${OMP_REASON}" OFF)
kfeature_row("Julia" "${JULIA_ENABLED}" "${JULIA_REASON}" OFF)
# From lib/core: NUMA and OpenSSL
if(DEFINED NUMA_ENABLED)
    kfeature_row("NUMA" "${NUMA_ENABLED}" "${NUMA_REASON}" OFF)
endif()
if(DEFINED OPENSSL_ENABLED)
    kfeature_row("OpenSSL" "${OPENSSL_ENABLED}" "${OPENSSL_REASON}" OFF)
endif()
if(DEFINED DPDK_ENABLED)
    kfeature_row("DPDK" "${DPDK_ENABLED}" "${DPDK_REASON} toggle: -DUSE_OLD_DPDK=ON" OFF)
endif()

# Build meta
kfeature_header("Build")
kfeature_kv("Build Type" "${CMAKE_BUILD_TYPE} (-DCMAKE_BUILD_TYPE=Debug|Release|Test)")
set(DOCS_ENABLED ${COMPILE_DOCS})
if(${COMPILE_DOCS})
    set(DOCS_REASON "enabled")
else()
    set(DOCS_REASON "disabled")
endif()
kfeature_row("Docs" "${DOCS_ENABLED}" "${DOCS_REASON}, toggle: -DCOMPILE_DOCS=ON/OFF" OFF)
set(TESTS_ENABLED ${WITH_TESTS})
if(${WITH_TESTS})
    set(TESTS_REASON "enabled")
else()
    set(TESTS_REASON "disabled")
endif()
kfeature_row("C++ Tests (lib)" "${TESTS_ENABLED}" "${TESTS_REASON} -DWITH_TESTS=ON/OFF)" OFF)
set(BOOSTTEST_ENABLED ${WITH_BOOST_TESTS})
if(${WITH_BOOST_TESTS})
    set(BOOSTTEST_REASON "enabled")
else()
    set(BOOSTTEST_REASON "disabled")
endif()
kfeature_row("Boost Tests" "${BOOSTTEST_ENABLED}"
             "${BOOSTTEST_REASON}, toggle: -DWITH_BOOST_TESTS=ON/OFF" OFF)
set(NOMEMLOCK_ENABLED ${NO_MEMLOCK})
if(${NO_MEMLOCK})
    set(NOMEMLOCK_REASON "enabled")
else()
    set(NOMEMLOCK_REASON "disabled")
endif()
kfeature_row("No Memlock" "${NOMEMLOCK_ENABLED}"
             "${NOMEMLOCK_REASON} (toggle: -DNO_MEMLOCK=ON/OFF)" OFF)
kfeature_row("ccache" "${CCACHE_ENABLED}" "${CCACHE_REASON}, toggle: -DCCACHE=ON/OFF" OFF)
set(WERROR_REASON "disabled")
if(${WERROR_ENABLED})
    set(WERROR_REASON "enabled")
endif()
kfeature_row("Warnings-as-errors" "${WERROR_ENABLED}" "${WERROR_REASON}, toggle: -DWERROR=ON/OFF"
             OFF)
set(IWYU_REASON "disabled")
if(${IWYU_ENABLED})
    set(IWYU_REASON "enabled")
endif()
kfeature_row("include-what-you-use" "${IWYU_ENABLED}" "${IWYU_REASON}, toggle: -DIWYU=ON/OFF" OFF)

# Compilers
kfeature_header("Compilers")
set(_C_VERS ${CMAKE_C_COMPILER_VERSION})
if(NOT _C_VERS)
    set(_C_VERS "unknown")
endif()
set(_CXX_VERS ${CMAKE_CXX_COMPILER_VERSION})
if(NOT _CXX_VERS)
    set(_CXX_VERS "unknown")
endif()
kfeature_kv("C" "${CMAKE_C_COMPILER_ID} ${_C_VERS} (${CMAKE_C_COMPILER})")
kfeature_kv("C++" "${CMAKE_CXX_COMPILER_ID} ${_CXX_VERS} (${CMAKE_CXX_COMPILER})")
if(CUDA_ENABLED)
    set(_CUDA_VERS ${CMAKE_CUDA_COMPILER_VERSION})
    if(NOT _CUDA_VERS)
        set(_CUDA_VERS "unknown")
    endif()
    kfeature_kv("CUDA" "NVCC ${_CUDA_VERS} (${CMAKE_CUDA_COMPILER})")
endif()

kmsg_status("")
