name: kotekan-ci-tests
on:
  pull_request:
    branches:
    - chord
    - develop
  push:
    branches:
    - chord
    - develop

env:
  REGISTRY: ghcr.io

jobs:

  # Kotekan docker image build and push
  kotekan-docker:
    permissions: write-all
    uses: ./.github/workflows/build_push_docker.yml

  github-kotekan-cpu-tests:
    name: "Kotekan Build Tests"
    needs: kotekan-docker
    uses: ./.github/workflows/test_kotekan_build.yml
    with:
      container_image: ${{ needs.kotekan-docker.outputs.docker_cpu_img_name }}
      ccache_key: ${{ matrix.ccache_key }}
      cmake_defs: ${{ matrix.cmake_defs }}
      post_build: ${{ matrix.post_build }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: test_basic_build
            name: "test build + no features"
            ccache_key: kotekan-test-gcc-cpu
            cmake_defs: &test_basic_build_opts >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=OFF -DNO_MEMLOCK=OFF
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=OFF -DUSE_HDF5=OFF -DUSE_GDAL=OFF
              -DUSE_AIRSPY=OFF -DUSE_LAPACK_BLAZE=OFF -DUSE_FFTW=OFF -DUSE_JULIA=OFF -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=ON
            post_build: ""   # nothing to run

          - id: test_build_pytests
            name: "test build + pytests tests"
            ccache_key: kotekan-test-gcc-cpu
            cmake_defs: &test_build_pytests_opts >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              PYTHONPATH=$GITHUB_WORKSPACE/python
              PYTEST_TIMEOUT=100
              cd $GITHUB_WORKSPACE/tests
              pytest -v -n auto -s --dist=loadfile --timeout="${PYTEST_TIMEOUT}" -x -m 'not serial'
              pytest -rP
              pytest -v -x -s --timeout="${PYTEST_TIMEOUT}" -m serial
              pytest -rP

          - id: test_build_boost
            name: "test build + boost tests"
            ccache_key: kotekan-test-gcc-cpu
            cmake_defs: &test_build_pytests_opts >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=ON
            post_build: |
              TEST_TIMEOUT=30
              bash $GITHUB_WORKSPACE/tests/boost/run_boost_tests.sh -v -t "${TEST_TIMEOUT}" $GITHUB_WORKSPACE/build-2404/tests/boost

          - id: release_pytest_gcc
            name: "Release build + pytest"
            ccache_key: kotekan-release-gcc-cpu
            cmake_defs: &release_build_gcc_opts >-
              -DCMAKE_BUILD_TYPE=Release -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=ON
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              PYTHONPATH=$GITHUB_WORKSPACE/python
              PYTEST_TIMEOUT=100
              cd $GITHUB_WORKSPACE/tests
              pytest -v -n auto -s --dist=loadfile --timeout="${PYTEST_TIMEOUT}" -x -m 'not serial'
              pytest -rP
              pytest -v -x -s --timeout="${PYTEST_TIMEOUT}" -m serial
              pytest -rP
