# This workflow runs suites of tests on both a local runner and github runners.
# Generally, it should be when pull requests are open/updated, or on direct pushes (uncommon).
# It calls the build_push_docker workflow to make sure the kotekan docker image exists,
# and the test_kotekan_build workflow for kotekan tests.
---
name: kotekan-ci-tests
on:
  pull_request:
    branches:
    - chord
    - develop
  push:
    branches:
    - chord
    - develop

env:
  REGISTRY: ghcr.io

jobs:

  # Kotekan docker image build and push
  kotekan-docker:
    permissions: write-all
    uses: ./.github/workflows/build_push_docker.yml

  kotekan-cpu-tests:
    name: CPU
    needs: kotekan-docker
    uses: ./.github/workflows/test_kotekan_build.yml
    with:
      container_image: ${{ needs.kotekan-docker.outputs.docker_cpu_img_name }}
      ccache_key: ${{ matrix.ccache_key }}
      cmake_defs: ${{ matrix.cmake_defs }}
      post_build: ${{ matrix.post_build }}
    strategy:
      fail-fast: false
      matrix:
        include:
          
          # Test gcc build + no features
          - id: test_gcc_basic
            ccache_key: kotekan-test-gcc-cpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=OFF -DNO_MEMLOCK=OFF
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=OFF -DUSE_HDF5=OFF -DUSE_GDAL=OFF
              -DUSE_AIRSPY=OFF -DUSE_LAPACK_BLAZE=OFF -DUSE_FFTW=OFF -DUSE_JULIA=OFF -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=ON
            post_build: ""   # nothing to run

          # Test gcc build + serial pytests
          - id: test_gcc_serial_pytests
            ccache_key: kotekan-test-gcc-cpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              PYTEST_TIMEOUT=60
              cd $GITHUB_WORKSPACE/tests
              uv run pytest -v -x -rs --durations=0 --timeout="${PYTEST_TIMEOUT}" -m serial

          # Test gcc build + parallel pytests
          - id: test_gcc_parallel_pytests
            ccache_key: kotekan-test-gcc-cpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              PYTEST_TIMEOUT=60
              cd $GITHUB_WORKSPACE/tests
              uv run pytest -v -n auto -rs --dist=loadfile --durations=0 --timeout="${PYTEST_TIMEOUT}" -x -m 'not serial'

          # Test gcc build + boost tests
          - id: test_gcc_boost
            ccache_key: kotekan-test-gcc-cpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=ON
            post_build: |
              TEST_TIMEOUT=30
              bash $GITHUB_WORKSPACE/tests/boost/run_boost_tests.sh -v -t "${TEST_TIMEOUT}" $GITHUB_WORKSPACE/build-2404/tests/boost

          # Release gcc build + serial pytests
          - id: release_gcc_serial_pytests
            ccache_key: kotekan-release-gcc-cpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Release -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              PYTEST_TIMEOUT=60
              cd $GITHUB_WORKSPACE/tests
              uv run pytest -v -x -rs --durations=0 --timeout="${PYTEST_TIMEOUT}" -m serial

          # Release gcc build + parallel pytests
          - id: release_gcc_parallel_pytests
            ccache_key: kotekan-release-gcc-cpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Release -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              PYTEST_TIMEOUT=60
              cd $GITHUB_WORKSPACE/tests
              uv run pytest -v -n auto -rs --dist=loadfile --durations=0 --timeout="${PYTEST_TIMEOUT}" -x -m 'not serial'

          # Test clang build
          - id: clang
            ccache_key: kotekan-test-clang-cpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
              -DUSE_OMP=ON -DUSE_NUMA=OFF -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=ON
            post_build: ""  # Any clang tests to run?

          # Release clang build
          - id: release_clang
            ccache_key: kotekan-release-clang-cpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Release -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
              -DUSE_OMP=ON -DUSE_NUMA=OFF -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=ON
            post_build: ""  # Any clang tests to run?

          # run yamls in config/ci-tests/cpu_batch
          - id: test-gcc-cpu-yaml
            ccache_key: kotekan-test-gcc-yaml
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=ON
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              bash $GITHUB_WORKSPACE/config/ci-tests/run_tests.sh $GITHUB_WORKSPACE/build-2404/kotekan/kotekan 2m $GITHUB_WORKSPACE/config/ci-tests/cpu_batch

          # Test gcc build with docs
          - id: local-docs
            ccache_key: kotekan-test-gcc-docs
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Release -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=OFF -DNO_MEMLOCK=ON
              -DUSE_CUDA=OFF -DUSE_HIP=OFF -DUSE_OPENCL=OFF
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=OFF
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF -DCOMPILE_DOCS=ON
            post_build: |
              cd $GITHUB_WORKSPACE/build-2404 && make docs

          # Run Linter
          - id: lint
            cmake_defs: ""
            post_build: |
              cd $GITHUB_WORKSPACE
              git config --global --add safe.directory $GITHUB_WORKSPACE
              bash ./tools/lint.sh


  kotekan-gpu-tests:
    name: "GPU"
    needs: kotekan-docker
    uses: ./.github/workflows/test_kotekan_build.yml
    with:
      container_image: ${{ needs.kotekan-docker.outputs.docker_gpu_img_name }}
      ccache_key: ${{ matrix.ccache_key }}
      cmake_defs: ${{ matrix.cmake_defs }}
      post_build: ${{ matrix.post_build }}
      runs_on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: true
      matrix:
        include:

          # Test gcc build + CUDA/OpenCL
          - id: test-gcc-cuda-opencl
            ccache_key: kotekan-test-gcc-gpu
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=ON -DUSE_HIP=OFF -DUSE_OPENCL=ON
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=ON
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=ON
            post_build: ""   # Any OpenCL-specific commands to test?
            runs_on: ubuntu-latest # github

          # run yamls in config/ci-tests/gpu_batch
          - id: test-gcc-gpu-yaml
            ccache_key: kotekan-test-gcc-yaml
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Test -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=ON -DUSE_HIP=OFF -DUSE_OPENCL=ON
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=ON
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              bash $GITHUB_WORKSPACE/config/ci-tests/run_tests.sh $GITHUB_WORKSPACE/build-2404/kotekan/kotekan 2m $GITHUB_WORKSPACE/config/ci-tests/gpu_batch
            runs_on: self-hosted

          # run yamls in config/ci-tests/gpu_batch
          - id: release-gcc-gpu-yaml
            ccache_key: kotekan-release-gcc-yaml
            cmake_defs: >-
              -DCMAKE_BUILD_TYPE=Release -DWERROR=ON
              -DCMAKE_LINK_WHAT_YOU_USE=ON -DCCACHE=ON
              -DUSE_OMP=ON -DUSE_NUMA=ON -DNO_MEMLOCK=ON
              -DUSE_CUDA=ON -DUSE_HIP=OFF -DUSE_OPENCL=ON
              -DUSE_ASDF=ON -DUSE_HDF5=ON -DUSE_GDAL=ON
              -DUSE_AIRSPY=ON -DUSE_LAPACK_BLAZE=ON -DUSE_FFTW=ON -DUSE_JULIA=ON -DUSE_DPDK=ON
              -DWITH_TESTS=ON -DWITH_BOOST_TESTS=OFF
            post_build: |
              bash $GITHUB_WORKSPACE/config/ci-tests/run_tests.sh $GITHUB_WORKSPACE/build-2404/kotekan/kotekan 2m $GITHUB_WORKSPACE/config/ci-tests/gpu_batch
            runs_on: self-hosted

          # /data dir test"
          - id: data-test
            cmake_defs: ""
            post_build: |
              # Try something with the persistent /data directory.
              touch /data/tmp
              ls /data
              rm /data/tmp
            runs_on: self-hosted


  github-uv-env-tests:
    name: "Github"
    runs-on: ubuntu-latest
    needs: build-docker-2404
    container:
      image: ${{ needs.build-docker-2404.outputs.docker_img_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:

          - id: uv-run-env
            name: "uv-run env file"
            post_build: |
              # Run pytest tests
              # PYTHONPATH=$GITHUB_WORKSPACE/python
              cd $GITHUB_WORKSPACE/tests/uv_test
              echo "PYTHONPATH=${GITHUB_WORKSPACE}/python:$PYTHONPATH" > gh_env_test
              cat gh_env_test
              echo $PYTHONPATH
              uv run --env-file gh_env_test -- hello.py

          - id: uv-run-env-export
            name: "uv-run env export file"
            post_build: |
              # Run pytest tests
              # PYTHONPATH=$GITHUB_WORKSPACE/python
              cd $GITHUB_WORKSPACE/tests/uv_test
              echo "export PYTHONPATH=${GITHUB_WORKSPACE}/python:$PYTHONPATH" > gh_env_test
              cat gh_env_test
              echo $PYTHONPATH
              uv run --env-file gh_env_test -- hello.py

          - id: vanilla
            name: "python"
            post_build: |
              # Run pytest tests
              # PYTHONPATH=$GITHUB_WORKSPACE/python
              echo $PYTHONPATH
              python3 hello.py

          - id: vanilla-env
            name: "python env"
            post_build: |
              # Run pytest tests
              PYTHONPATH=$GITHUB_WORKSPACE/python
              echo $PYTHONPATH
              python3 hello.py

          - id: vanilla-env-export
            name: "python env export"
            post_build: |
              # Run pytest tests
              export PYTHONPATH=$GITHUB_WORKSPACE/python
              echo $PYTHONPATH
              python3 hello.py

          - id: vanilla-prefix
            name: "python env"
            post_build: |
              # Run pytest tests
              echo $PYTHONPATH
              PYTHONPATH="${GITHUB_WORKSPACE}/python:$PYTHONPATH" python3 hello.py

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-test-2404-${{ github.sha }}
          restore-keys: |
            ccache-test-2404

      - name: Print working environment details
        run: |
          echo "==========="
          pwd
          echo "==========="
          ls -la
          echo "==========="
          env
          echo "==========="
          df -h
          echo "==========="
          free -h
          echo "==========="
          lscpu

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.7"

      - name: Setup uv Python
        run: uv python install

      - name: Setup uv Python environment
        run: uv sync --locked --all-extras --dev

      - name: Post-build commands
        if: matrix.post_build
        shell: bash
        run: |
          set -euo pipefail
          # Run any commands specified ...
          ${{ matrix.post_build }}
