# This workflow can be used to trigger manual builds on github.
# This will only work if/when it exists on the default branch.
---
name: manual-docker-image-build

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Tag/branch name to use for the Docker images (will be sanitized for tag)"
        required: true
        default: 'develop'
        type: string

jobs:
  manual-build-docker:
    uses: ./.github/workflows/build_push_docker.yaml
    with:
      build_branch: ${{ github.event.inputs.build_branch }}
